extendTopic("media", "Phim ảnh, âm nhạc & tin tức", [
  ["episode", "n", "ˈepəsoʊd", "tập (phim)", "I watched three episodes last night.", "Tối qua tôi xem ba tập phim."],
  ["series", "n", "ˈsɪriːz", "loạt phim, phim bộ", "This Korean series has sixteen episodes.", "Bộ phim Hàn này có mười sáu tập."],
  ["movie theater", "n", "ˈmuːvi ˌθiːətɚ", "rạp chiếu phim", "Let's meet at the movie theater at seven.", "Hẹn gặp ở rạp chiếu phim lúc bảy giờ nhé."],
  ["actor", "n", "ˈæktɚ", "nam diễn viên", "He is my favorite actor.", "Anh ấy là nam diễn viên tôi thích nhất."],
  ["actress", "n", "ˈæktrəs", "nữ diễn viên", "The actress won an award this year.", "Nữ diễn viên đó đã giành giải thưởng năm nay."],
  ["director", "n", "dəˈrektɚ", "đạo diễn", "The director made a very funny movie.", "Đạo diễn đã làm một bộ phim rất hài hước."],
  ["trailer", "n", "ˈtreɪlɚ", "đoạn giới thiệu phim", "The trailer looks really exciting.", "Đoạn giới thiệu phim trông rất hấp dẫn."],
  ["subtitles", "n", "ˈsʌbˌtaɪtəlz", "phụ đề", "I watch English movies with subtitles.", "Tôi xem phim tiếng Anh có phụ đề."],
  ["plot", "n", "plɑːt", "cốt truyện", "The plot was hard to follow.", "Cốt truyện khó theo dõi quá."],
  ["ending", "n", "ˈendɪŋ", "cái kết", "I didn't like the ending of the movie.", "Tôi không thích cái kết của bộ phim."],
  ["scene", "n", "siːn", "cảnh (phim)", "The last scene made me cry.", "Cảnh cuối làm tôi khóc."],
  ["character", "n", "ˈkerəktɚ", "nhân vật", "Who is your favorite character?", "Nhân vật bạn thích nhất là ai?"],
  ["comedy", "n", "ˈkɑːmədi", "phim hài", "Let's watch a comedy tonight.", "Tối nay mình xem phim hài đi."],
  ["horror movie", "n", "ˈhɔːrɚ ˌmuːvi", "phim kinh dị", "I can't watch horror movies alone.", "Tôi không dám xem phim kinh dị một mình."],
  ["cartoon", "n", "kɑːrˈtuːn", "phim hoạt hình", "My son watches cartoons every morning.", "Con trai tôi xem phim hoạt hình mỗi sáng."],
  ["documentary", "n", "ˌdɑːkjəˈmentɚi", "phim tài liệu", "We watched a documentary about the ocean.", "Chúng tôi đã xem một phim tài liệu về đại dương."],
  ["song", "n", "sɔːŋ", "bài hát", "This song is very popular right now.", "Bài hát này đang rất nổi tiếng."],
  ["singer", "n", "ˈsɪŋɚ", "ca sĩ", "She wants to become a singer.", "Cô ấy muốn trở thành ca sĩ."],
  ["band", "n", "bænd", "ban nhạc", "My brother plays guitar in a band.", "Anh tôi chơi guitar trong một ban nhạc."],
  ["album", "n", "ˈælbəm", "album nhạc", "Their new album comes out next week.", "Album mới của họ ra mắt vào tuần sau."],
  ["lyrics", "n", "ˈlɪrɪks", "lời bài hát", "I don't understand the lyrics of this song.", "Tôi không hiểu lời bài hát này."],
  ["concert", "n", "ˈkɑːnsɚt", "buổi hòa nhạc", "We went to a concert last Saturday.", "Thứ Bảy tuần trước chúng tôi đi xem hòa nhạc."],
  ["playlist", "n", "ˈpleɪlɪst", "danh sách phát", "I made a playlist for the road trip.", "Tôi đã tạo một danh sách nhạc cho chuyến đi."],
  ["podcast", "n", "ˈpɑːdkæst", "podcast (chương trình âm thanh)", "I listen to a podcast on my way to work.", "Tôi nghe podcast trên đường đi làm."],
  ["channel", "n", "ˈtʃænəl", "kênh", "What channel is the game on?", "Trận đấu chiếu trên kênh nào?"],
  ["audience", "n", "ˈɑːdiəns", "khán giả", "The audience loved the show.", "Khán giả rất thích buổi diễn."],
  ["stream", "v", "striːm", "phát trực tuyến, xem trực tuyến", "You can stream the movie online.", "Bạn có thể xem bộ phim trực tuyến."],
  ["subscribe", "v", "səbˈskraɪb", "đăng ký theo dõi", "Please subscribe to my channel.", "Hãy đăng ký kênh của tôi nhé."],
  ["post", "v", "poʊst", "đăng (bài)", "She posts photos on Instagram every day.", "Cô ấy đăng ảnh lên Instagram mỗi ngày."],
  ["share", "v", "ʃer", "chia sẻ", "Can you share that video with me?", "Bạn chia sẻ video đó cho tôi được không?"],
  ["comment", "n", "ˈkɑːment", "bình luận", "Thanks for all your nice comments.", "Cảm ơn mọi người vì những bình luận dễ thương."],
  ["follower", "n", "ˈfɑːloʊɚ", "người theo dõi", "He has over ten thousand followers.", "Anh ấy có hơn mười nghìn người theo dõi."],
  ["go viral", "phr", "ˌɡoʊ ˈvaɪrəl", "lan truyền nhanh, nổi rần rần", "Her dance video went viral overnight.", "Video nhảy của cô ấy nổi rần rần chỉ sau một đêm."],
  ["headline", "n", "ˈhedlaɪn", "tiêu đề báo", "I only read the headlines in the morning.", "Buổi sáng tôi chỉ đọc các tiêu đề báo."],
  ["article", "n", "ˈɑːrtɪkəl", "bài báo", "I read an interesting article about coffee.", "Tôi đã đọc một bài báo thú vị về cà phê."],
  ["journalist", "n", "ˈdʒɝːnəlɪst", "nhà báo", "The journalist asked the mayor a question.", "Nhà báo đã đặt câu hỏi cho thị trưởng."],
  ["report", "v", "rɪˈpɔːrt", "đưa tin, báo cáo", "The news reported a big fire downtown.", "Bản tin đưa tin về một vụ cháy lớn ở trung tâm."],
  ["advertisement", "n", "ˌædvɚˈtaɪzmənt", "quảng cáo", "There are too many advertisements on TV.", "Trên tivi có quá nhiều quảng cáo."],
  ["fake news", "n", "ˌfeɪk ˈnuːz", "tin giả", "Don't share fake news on Facebook.", "Đừng chia sẻ tin giả trên Facebook."],
  ["spoiler", "n", "ˈspɔɪlɚ", "tiết lộ nội dung phim", "No spoilers, please! I haven't seen it yet.", "Đừng tiết lộ nhé! Tôi chưa xem mà."],
]);

extendTopic("business", "Kinh doanh & email công việc", [
  ["customer", "n", "ˈkʌstəmɚ", "khách hàng", "The customer wants to change her order.", "Khách hàng muốn thay đổi đơn hàng của cô ấy."],
  ["client", "n", "ˈklaɪənt", "khách hàng (đối tác dịch vụ)", "I have lunch with a client today.", "Hôm nay tôi ăn trưa với một khách hàng."],
  ["invoice", "n", "ˈɪnvɔɪs", "hóa đơn", "Please send me the invoice by Friday.", "Vui lòng gửi tôi hóa đơn trước thứ Sáu."],
  ["contract", "n", "ˈkɑːntrækt", "hợp đồng", "Please read the contract carefully before signing.", "Vui lòng đọc kỹ hợp đồng trước khi ký."],
  ["attach", "v", "əˈtætʃ", "đính kèm", "I have attached the file to this email.", "Tôi đã đính kèm tệp vào email này."],
  ["attachment", "n", "əˈtætʃmənt", "tệp đính kèm", "I can't open the attachment.", "Tôi không mở được tệp đính kèm."],
  ["confirm", "v", "kənˈfɝːm", "xác nhận", "Could you confirm the time of the meeting?", "Anh có thể xác nhận thời gian cuộc họp không?"],
  ["schedule a call", "phr", "ˈskedʒuːl ə ˈkɑːl", "hẹn lịch gọi điện", "Let's schedule a call for next Monday.", "Mình hẹn lịch gọi vào thứ Hai tuần sau nhé."],
  ["profit", "n", "ˈprɑːfɪt", "lợi nhuận", "Our profit went up this year.", "Lợi nhuận của chúng tôi tăng trong năm nay."],
  ["loss", "n", "lɔːs", "khoản lỗ, thua lỗ", "The shop made a loss last month.", "Cửa hàng bị lỗ vào tháng trước."],
  ["revenue", "n", "ˈrevənuː", "doanh thu", "Our revenue doubled in two years.", "Doanh thu của chúng tôi tăng gấp đôi trong hai năm."],
  ["budget", "n", "ˈbʌdʒɪt", "ngân sách", "We don't have the budget for a new car.", "Chúng tôi không có ngân sách mua xe mới."],
  ["cost", "n", "kɔːst", "chi phí", "We need to reduce our costs.", "Chúng ta cần giảm chi phí."],
  ["sales", "n", "seɪlz", "doanh số; bộ phận kinh doanh", "Sales were very good in December.", "Doanh số tháng Mười Hai rất tốt."],
  ["product", "n", "ˈprɑːdʌkt", "sản phẩm", "Our new product is selling well.", "Sản phẩm mới của chúng tôi đang bán chạy."],
  ["service", "n", "ˈsɝːvɪs", "dịch vụ", "They offer a delivery service.", "Họ có dịch vụ giao hàng."],
  ["company", "n", "ˈkʌmpəni", "công ty", "I work for a small software company.", "Tôi làm cho một công ty phần mềm nhỏ."],
  ["manager", "n", "ˈmænɪdʒɚ", "quản lý", "I need to ask my manager first.", "Tôi cần hỏi quản lý trước đã."],
  ["department", "n", "dɪˈpɑːrtmənt", "phòng, ban", "She works in the marketing department.", "Cô ấy làm ở phòng marketing."],
  ["staff", "n", "stæf", "nhân viên (nói chung)", "All staff must attend the training.", "Tất cả nhân viên phải tham gia buổi đào tạo."],
  ["supplier", "n", "səˈplaɪɚ", "nhà cung cấp", "We are looking for a cheaper supplier.", "Chúng tôi đang tìm nhà cung cấp rẻ hơn."],
  ["partner", "n", "ˈpɑːrtnɚ", "đối tác", "They are our business partner in Japan.", "Họ là đối tác kinh doanh của chúng tôi ở Nhật."],
  ["negotiate", "v", "nəˈɡoʊʃieɪt", "đàm phán, thương lượng", "We negotiated a better price.", "Chúng tôi đã thương lượng được giá tốt hơn."],
  ["deal", "n", "diːl", "thỏa thuận, hợp đồng làm ăn", "We finally made a deal with them.", "Cuối cùng chúng tôi đã đạt được thỏa thuận với họ."],
  ["sign", "v", "saɪn", "ký", "Please sign here and here.", "Vui lòng ký vào chỗ này và chỗ này."],
  ["payment", "n", "ˈpeɪmənt", "khoản thanh toán", "We haven't received your payment yet.", "Chúng tôi chưa nhận được khoản thanh toán của anh."],
  ["quote", "n", "kwoʊt", "báo giá", "Can you send us a quote for this job?", "Anh gửi chúng tôi báo giá cho việc này được không?"],
  ["deliver", "v", "dɪˈlɪvɚ", "giao (hàng)", "We will deliver the goods on Tuesday.", "Chúng tôi sẽ giao hàng vào thứ Ba."],
  ["reply", "v", "rɪˈplaɪ", "trả lời, hồi âm", "Sorry for not replying sooner.", "Xin lỗi vì đã không trả lời sớm hơn."],
  ["forward", "v", "ˈfɔːrwɚd", "chuyển tiếp (email)", "I'll forward you his email.", "Tôi sẽ chuyển tiếp email của anh ấy cho bạn."],
  ["follow up", "phr", "ˌfɑːloʊ ˈʌp", "liên hệ lại, theo dõi tiếp", "I'm writing to follow up on our meeting.", "Tôi viết thư này để trao đổi tiếp về cuộc họp của chúng ta."],
  ["reschedule", "v", "ˌriːˈskedʒuːl", "dời lịch, sắp xếp lại lịch", "Can we reschedule the call to Thursday?", "Mình dời cuộc gọi sang thứ Năm được không?"],
  ["postpone", "v", "poʊstˈpoʊn", "hoãn lại", "The event was postponed because of the rain.", "Sự kiện bị hoãn lại vì trời mưa."],
  ["cancel", "v", "ˈkænsəl", "hủy", "I'm sorry, I have to cancel our appointment.", "Xin lỗi, tôi phải hủy cuộc hẹn của chúng ta."],
  ["presentation", "n", "ˌprezənˈteɪʃən", "bài thuyết trình", "I'm nervous about my presentation tomorrow.", "Tôi lo lắng về bài thuyết trình ngày mai."],
  ["agenda", "n", "əˈdʒendə", "chương trình họp", "What's on the agenda for today?", "Chương trình họp hôm nay có gì?"],
  ["feedback", "n", "ˈfiːdbæk", "phản hồi, góp ý", "Thanks for your feedback on my report.", "Cảm ơn góp ý của anh về báo cáo của tôi."],
  ["goal", "n", "ɡoʊl", "mục tiêu", "Our goal is to double sales next year.", "Mục tiêu của chúng tôi là tăng gấp đôi doanh số năm sau."],
  ["Best regards", "phr", "ˌbest rɪˈɡɑːrdz", "Trân trọng (cuối email)", "Best regards, Lan Nguyen", "Trân trọng, Nguyễn Lan"],
  ["in charge of", "phr", "ɪn ˈtʃɑːrdʒ əv", "phụ trách", "Who is in charge of this project?", "Ai phụ trách dự án này?"],
]);
