// Bộ từ bổ sung C: thiên nhiên, động vật, cơ thể, quần áo (4 chủ đề x 40 từ).
extendTopic("nature", "Thiên nhiên & môi trường", [
  ["mountain", "n", "ˈmaʊntən", "núi", "We climbed the mountain early in the morning.", "Chúng tôi leo núi từ sáng sớm."],
  ["river", "n", "ˈrɪvɚ", "sông", "The Red River flows through Hanoi.", "Sông Hồng chảy qua Hà Nội."],
  ["lake", "n", "leɪk", "hồ", "People walk around the lake every evening.", "Mọi người đi dạo quanh hồ mỗi tối."],
  ["forest", "n", "ˈfɔːrɪst", "rừng", "Many animals live in this forest.", "Nhiều loài động vật sống trong khu rừng này."],
  ["beach", "n", "biːtʃ", "bãi biển", "We spent the whole day at the beach.", "Chúng tôi ở bãi biển cả ngày."],
  ["island", "n", "ˈaɪlənd", "hòn đảo", "Phu Quoc is a beautiful island.", "Phú Quốc là một hòn đảo đẹp."],
  ["valley", "n", "ˈvæli", "thung lũng", "There is a small village in the valley.", "Có một ngôi làng nhỏ trong thung lũng."],
  ["hill", "n", "hɪl", "đồi", "The house is on top of a hill.", "Ngôi nhà nằm trên đỉnh đồi."],
  ["waterfall", "n", "ˈwɑːtɚfɔːl", "thác nước", "We swam near the waterfall.", "Chúng tôi bơi gần thác nước."],
  ["desert", "n", "ˈdezɚt", "sa mạc", "It rarely rains in the desert.", "Ở sa mạc hiếm khi có mưa."],
  ["field", "n", "fiːld", "cánh đồng", "The rice fields turn yellow in autumn.", "Những cánh đồng lúa chuyển vàng vào mùa thu."],
  ["cave", "n", "keɪv", "hang động", "Son Doong is the largest cave in the world.", "Sơn Đoòng là hang động lớn nhất thế giới."],
  ["coast", "n", "koʊst", "bờ biển", "They live in a town on the coast.", "Họ sống ở một thị trấn ven biển."],
  ["ocean", "n", "ˈoʊʃən", "đại dương", "Plastic is a big problem for the ocean.", "Nhựa là một vấn đề lớn đối với đại dương."],
  ["rock", "n", "rɑːk", "đá, tảng đá", "The kids sat on a big rock.", "Bọn trẻ ngồi trên một tảng đá lớn."],
  ["sand", "n", "sænd", "cát", "The sand on this beach is very white.", "Cát ở bãi biển này rất trắng."],
  ["soil", "n", "sɔɪl", "đất (trồng trọt)", "This soil is good for growing coffee.", "Đất này tốt để trồng cà phê."],
  ["grass", "n", "ɡræs", "cỏ", "Please don't walk on the grass.", "Vui lòng không giẫm lên cỏ."],
  ["leaf", "n", "liːf", "lá cây", "The leaves fall off the trees in autumn.", "Lá rụng khỏi cây vào mùa thu."],
  ["branch", "n", "bræntʃ", "cành cây", "A bird is sitting on the branch.", "Một con chim đang đậu trên cành cây."],
  ["root", "n", "ruːt", "rễ cây", "The roots of this tree are very deep.", "Rễ của cái cây này rất sâu."],
  ["seed", "n", "siːd", "hạt giống", "She planted some seeds in the garden.", "Cô ấy gieo vài hạt giống trong vườn."],
  ["plant", "v", "plænt", "trồng (cây)", "We planted a mango tree last year.", "Năm ngoái chúng tôi đã trồng một cây xoài."],
  ["bloom", "v", "bluːm", "nở hoa", "Peach flowers bloom before Tet.", "Hoa đào nở trước Tết."],
  ["environment", "n", "ɪnˈvaɪrənmənt", "môi trường", "We should protect the environment.", "Chúng ta nên bảo vệ môi trường."],
  ["pollution", "n", "pəˈluːʃən", "sự ô nhiễm", "Air pollution is bad in big cities.", "Ô nhiễm không khí ở các thành phố lớn rất tệ."],
  ["pollute", "v", "pəˈluːt", "làm ô nhiễm", "Factories pollute the river with chemicals.", "Các nhà máy làm ô nhiễm dòng sông bằng hóa chất."],
  ["recycle", "v", "ˌriːˈsaɪkəl", "tái chế", "We recycle paper and plastic bottles.", "Chúng tôi tái chế giấy và chai nhựa."],
  ["trash", "n", "træʃ", "rác", "Please put your trash in the bin.", "Vui lòng bỏ rác vào thùng."],
  ["plastic bag", "n", "ˌplæstɪk ˈbæɡ", "túi ni lông", "I try not to use plastic bags.", "Tôi cố gắng không dùng túi ni lông."],
  ["cliff", "n", "klɪf", "vách đá", "Don't stand too close to the edge of the cliff.", "Đừng đứng quá gần mép vách đá."],
  ["litter", "v", "ˈlɪtɚ", "xả rác", "Don't litter in the park.", "Đừng xả rác trong công viên."],
  ["protect", "v", "prəˈtekt", "bảo vệ", "Trees protect the soil from floods.", "Cây cối bảo vệ đất khỏi lũ lụt."],
  ["climate change", "n", "ˈklaɪmət ˌtʃeɪndʒ", "biến đổi khí hậu", "Climate change affects farmers in the Mekong Delta.", "Biến đổi khí hậu ảnh hưởng đến nông dân ở đồng bằng sông Cửu Long."],
  ["energy", "n", "ˈenɚdʒi", "năng lượng", "We need to save energy at home.", "Chúng ta cần tiết kiệm năng lượng ở nhà."],
  ["solar panel", "n", "ˌsoʊlɚ ˈpænəl", "tấm pin mặt trời", "They put solar panels on the roof.", "Họ lắp tấm pin mặt trời trên mái nhà."],
  ["cut down", "phr", "kʌt ˈdaʊn", "chặt, đốn (cây)", "People cut down too many trees here.", "Người ta chặt quá nhiều cây ở đây."],
  ["endangered", "adj", "ɪnˈdeɪndʒɚd", "có nguy cơ tuyệt chủng", "The saola is an endangered animal.", "Sao la là loài động vật có nguy cơ tuyệt chủng."],
  ["natural", "adj", "ˈnætʃɚəl", "tự nhiên", "This park keeps its natural beauty.", "Công viên này giữ được vẻ đẹp tự nhiên."],
  ["fresh air", "n", "ˌfreʃ ˈer", "không khí trong lành", "I love the fresh air in the countryside.", "Tôi thích không khí trong lành ở nông thôn."],
]);

extendTopic("animals", "Động vật", [
  ["buffalo", "n", "ˈbʌfəloʊ", "con trâu", "Farmers used buffaloes to plow the fields.", "Nông dân dùng trâu để cày ruộng."],
  ["cow", "n", "kaʊ", "con bò", "The cows are eating grass in the field.", "Những con bò đang ăn cỏ ngoài đồng."],
  ["pig", "n", "pɪɡ", "con lợn, con heo", "My grandparents raise pigs on their farm.", "Ông bà tôi nuôi lợn ở trang trại."],
  ["chicken", "n", "ˈtʃɪkən", "con gà", "The chickens wake us up every morning.", "Lũ gà đánh thức chúng tôi mỗi sáng."],
  ["duck", "n", "dʌk", "con vịt", "Some ducks are swimming in the pond.", "Vài con vịt đang bơi trong ao."],
  ["goat", "n", "ɡoʊt", "con dê", "Goats can climb steep hills.", "Dê có thể leo những ngọn đồi dốc."],
  ["sheep", "n", "ʃiːp", "con cừu", "There are many sheep on the farm.", "Có nhiều cừu ở trang trại."],
  ["horse", "n", "hɔːrs", "con ngựa", "Have you ever ridden a horse?", "Bạn đã bao giờ cưỡi ngựa chưa?"],
  ["rabbit", "n", "ˈræbɪt", "con thỏ", "My sister keeps a white rabbit.", "Em gái tôi nuôi một con thỏ trắng."],
  ["mouse", "n", "maʊs", "con chuột", "I saw a mouse in the kitchen.", "Tôi thấy một con chuột trong bếp."],
  ["snake", "n", "sneɪk", "con rắn", "Be careful, there are snakes in the grass.", "Cẩn thận, có rắn trong bụi cỏ."],
  ["frog", "n", "frɑːɡ", "con ếch", "You can hear frogs after the rain.", "Sau cơn mưa có thể nghe tiếng ếch kêu."],
  ["monkey", "n", "ˈmʌŋki", "con khỉ", "A monkey took my banana!", "Một con khỉ đã lấy quả chuối của tôi!"],
  ["elephant", "n", "ˈeləfənt", "con voi", "Elephants live in Yok Don National Park.", "Voi sống ở Vườn quốc gia Yok Đôn."],
  ["tiger", "n", "ˈtaɪɡɚ", "con hổ", "Tigers are very strong and fast.", "Hổ rất khỏe và nhanh."],
  ["lion", "n", "ˈlaɪən", "con sư tử", "The lion is sleeping under a tree.", "Con sư tử đang ngủ dưới gốc cây."],
  ["bear", "n", "ber", "con gấu", "Bears like to eat honey.", "Gấu thích ăn mật ong."],
  ["deer", "n", "dɪr", "con hươu, con nai", "We saw a deer in the forest.", "Chúng tôi thấy một con nai trong rừng."],
  ["wolf", "n", "wʊlf", "con sói", "Wolves usually hunt in groups.", "Sói thường săn mồi theo bầy."],
  ["fox", "n", "fɑːks", "con cáo", "The fox ran into the woods.", "Con cáo chạy vào rừng."],
  ["parrot", "n", "ˈpærət", "con vẹt", "Our parrot can say hello.", "Con vẹt nhà tôi biết nói xin chào."],
  ["eagle", "n", "ˈiːɡəl", "chim đại bàng", "An eagle flew high above the mountain.", "Một con đại bàng bay cao trên núi."],
  ["owl", "n", "aʊl", "con cú", "Owls hunt at night.", "Cú săn mồi vào ban đêm."],
  ["shark", "n", "ʃɑːrk", "cá mập", "Most sharks don't attack people.", "Hầu hết cá mập không tấn công người."],
  ["whale", "n", "weɪl", "cá voi", "The whale is the largest animal in the sea.", "Cá voi là loài vật lớn nhất ở biển."],
  ["dolphin", "n", "ˈdɑːlfɪn", "cá heo", "Dolphins are very smart animals.", "Cá heo là loài vật rất thông minh."],
  ["turtle", "n", "ˈtɝːtəl", "con rùa", "Sea turtles lay their eggs on the beach.", "Rùa biển đẻ trứng trên bãi biển."],
  ["crab", "n", "kræb", "con cua", "We ate steamed crab for dinner.", "Chúng tôi ăn cua hấp cho bữa tối."],
  ["shrimp", "n", "ʃrɪmp", "con tôm", "This soup has shrimp and vegetables.", "Món canh này có tôm và rau."],
  ["mosquito", "n", "məˈskiːtoʊ", "con muỗi", "There are a lot of mosquitoes tonight.", "Tối nay có rất nhiều muỗi."],
  ["ant", "n", "ænt", "con kiến", "Ants found the sugar on the table.", "Kiến đã tìm thấy đường trên bàn."],
  ["bee", "n", "biː", "con ong", "A bee stung me on the hand.", "Một con ong đã đốt vào tay tôi."],
  ["butterfly", "n", "ˈbʌtɚflaɪ", "con bướm", "Butterflies love the flowers in our garden.", "Bướm rất thích hoa trong vườn nhà tôi."],
  ["spider", "n", "ˈspaɪdɚ", "con nhện", "My sister is afraid of spiders.", "Em gái tôi sợ nhện."],
  ["cockroach", "n", "ˈkɑːkroʊtʃ", "con gián", "I hate cockroaches in the kitchen.", "Tôi ghét gián trong nhà bếp."],
  ["pet", "n", "pet", "thú cưng", "Do you have any pets?", "Bạn có nuôi thú cưng nào không?"],
  ["feed", "v", "fiːd", "cho ăn", "Can you feed the cat tonight?", "Tối nay bạn cho mèo ăn được không?"],
  ["bark", "v", "bɑːrk", "(chó) sủa", "The dog barks at every stranger.", "Con chó sủa mỗi khi thấy người lạ."],
  ["wild", "adj", "waɪld", "hoang dã", "Wild animals should not be kept as pets.", "Không nên nuôi động vật hoang dã làm thú cưng."],
  ["tail", "n", "teɪl", "cái đuôi", "The dog is wagging its tail.", "Con chó đang vẫy đuôi."],
]);

extendTopic("body", "Cơ thể người", [
  ["head", "n", "hed", "cái đầu", "She hit her head on the door.", "Cô ấy bị đập đầu vào cửa."],
  ["hair", "n", "her", "tóc", "My mother has long black hair.", "Mẹ tôi có mái tóc dài màu đen."],
  ["face", "n", "feɪs", "khuôn mặt", "Wash your face before going to bed.", "Rửa mặt trước khi đi ngủ nhé."],
  ["forehead", "n", "ˈfɔːrhed", "trán", "She touched his forehead to check for fever.", "Cô ấy sờ trán anh ấy xem có sốt không."],
  ["eyebrow", "n", "ˈaɪbraʊ", "lông mày", "He has thick eyebrows like his father.", "Anh ấy có lông mày rậm giống bố."],
  ["nose", "n", "noʊz", "cái mũi", "My nose is red from the cold.", "Mũi tôi đỏ lên vì lạnh."],
  ["cheek", "n", "tʃiːk", "má", "The baby has round, pink cheeks.", "Em bé có đôi má tròn, hồng hào."],
  ["chin", "n", "tʃɪn", "cằm", "He has a small scar on his chin.", "Anh ấy có một vết sẹo nhỏ ở cằm."],
  ["lip", "n", "lɪp", "môi", "My lips get dry in winter.", "Môi tôi bị khô vào mùa đông."],
  ["tooth", "n", "tuːθ", "răng", "I have a bad tooth, so I need a dentist.", "Tôi bị sâu một chiếc răng nên cần đi nha sĩ."],
  ["tongue", "n", "tʌŋ", "lưỡi", "I burned my tongue on the hot soup.", "Tôi bị bỏng lưỡi vì canh nóng."],
  ["ear", "n", "ɪr", "tai", "She whispered something in my ear.", "Cô ấy thì thầm điều gì đó vào tai tôi."],
  ["neck", "n", "nek", "cổ", "My neck hurts from using my phone too much.", "Cổ tôi đau vì dùng điện thoại quá nhiều."],
  ["shoulder", "n", "ˈʃoʊldɚ", "vai", "He carried the bag on his shoulder.", "Anh ấy vác cái túi trên vai."],
  ["arm", "n", "ɑːrm", "cánh tay", "She broke her arm playing volleyball.", "Cô ấy bị gãy tay khi chơi bóng chuyền."],
  ["elbow", "n", "ˈelboʊ", "khuỷu tay", "Don't put your elbows on the table.", "Đừng chống khuỷu tay lên bàn."],
  ["wrist", "n", "rɪst", "cổ tay", "He wears a watch on his left wrist.", "Anh ấy đeo đồng hồ ở cổ tay trái."],
  ["finger", "n", "ˈfɪŋɡɚ", "ngón tay", "I cut my finger while cooking.", "Tôi bị đứt tay khi nấu ăn."],
  ["thumb", "n", "θʌm", "ngón tay cái", "He gave me a thumbs-up.", "Anh ấy giơ ngón tay cái với tôi."],
  ["nail", "n", "neɪl", "móng tay, móng chân", "Stop biting your nails!", "Đừng cắn móng tay nữa!"],
  ["chest", "n", "tʃest", "ngực", "I felt a pain in my chest.", "Tôi thấy đau ở ngực."],
  ["back", "n", "bæk", "lưng", "Sitting all day makes my back hurt.", "Ngồi cả ngày làm tôi đau lưng."],
  ["stomach", "n", "ˈstʌmək", "bụng, dạ dày", "I have a pain in my stomach.", "Tôi bị đau bụng."],
  ["waist", "n", "weɪst", "eo, thắt lưng", "These pants are too big at the waist.", "Cái quần này rộng ở phần eo."],
  ["hip", "n", "hɪp", "hông", "She stood with her hands on her hips.", "Cô ấy đứng chống nạnh."],
  ["leg", "n", "leɡ", "chân (cẳng chân)", "My legs are tired after the long walk.", "Chân tôi mỏi sau chuyến đi bộ dài."],
  ["knee", "n", "niː", "đầu gối", "He hurt his knee playing football.", "Anh ấy bị đau đầu gối khi đá bóng."],
  ["ankle", "n", "ˈæŋkəl", "mắt cá chân", "I twisted my ankle on the stairs.", "Tôi bị trẹo mắt cá chân trên cầu thang."],
  ["heel", "n", "hiːl", "gót chân", "These new shoes hurt my heels.", "Đôi giày mới này làm đau gót chân tôi."],
  ["toe", "n", "toʊ", "ngón chân", "I hit my toe on the table.", "Tôi bị va ngón chân vào bàn."],
  ["skin", "n", "skɪn", "da", "Use sunscreen to protect your skin.", "Hãy dùng kem chống nắng để bảo vệ da."],
  ["bone", "n", "boʊn", "xương", "Milk is good for your bones.", "Sữa tốt cho xương."],
  ["heart", "n", "hɑːrt", "tim", "My heart was beating very fast.", "Tim tôi đập rất nhanh."],
  ["blood", "n", "blʌd", "máu", "He gives blood twice a year.", "Anh ấy hiến máu hai lần một năm."],
  ["blink", "v", "blɪŋk", "chớp mắt", "Try to blink more when using a computer.", "Hãy cố chớp mắt nhiều hơn khi dùng máy tính."],
  ["sneeze", "v", "sniːz", "hắt hơi", "Dust always makes me sneeze.", "Bụi lúc nào cũng làm tôi hắt hơi."],
  ["yawn", "v", "jɑːn", "ngáp", "He kept yawning during the meeting.", "Anh ấy cứ ngáp suốt buổi họp."],
  ["sweat", "v", "swet", "đổ mồ hôi", "I sweat a lot when I run.", "Tôi đổ mồ hôi rất nhiều khi chạy."],
  ["breathe", "v", "briːð", "thở", "Breathe slowly and try to relax.", "Hãy thở chậm và cố thư giãn."],
  ["nod", "v", "nɑːd", "gật đầu", "She nodded and smiled at me.", "Cô ấy gật đầu và mỉm cười với tôi."],
]);

extendTopic("clothes", "Quần áo & ngoại hình", [
  ["shirt", "n", "ʃɝːt", "áo sơ mi", "He wears a white shirt to work.", "Anh ấy mặc áo sơ mi trắng đi làm."],
  ["T-shirt", "n", "ˈtiː ʃɝːt", "áo phông, áo thun", "I bought a T-shirt at the market.", "Tôi đã mua một chiếc áo phông ở chợ."],
  ["jeans", "n", "dʒiːnz", "quần bò, quần jean", "She usually wears jeans on weekends.", "Cô ấy thường mặc quần jean vào cuối tuần."],
  ["pants", "n", "pænts", "quần dài", "These pants are too long for me.", "Cái quần này quá dài so với tôi."],
  ["shorts", "n", "ʃɔːrts", "quần short, quần đùi", "It's hot, so I'm wearing shorts.", "Trời nóng nên tôi mặc quần short."],
  ["skirt", "n", "skɝːt", "chân váy", "Her school uniform has a blue skirt.", "Đồng phục của cô ấy có chân váy màu xanh."],
  ["dress", "n", "dres", "váy liền, đầm", "She wore a red dress to the party.", "Cô ấy mặc một chiếc đầm đỏ đến bữa tiệc."],
  ["jacket", "n", "ˈdʒækɪt", "áo khoác", "Take a jacket, it's cold outside.", "Mang áo khoác đi, ngoài trời lạnh đấy."],
  ["coat", "n", "koʊt", "áo choàng, áo khoác dài", "I need a warm coat for my trip to Korea.", "Tôi cần một chiếc áo khoác ấm cho chuyến đi Hàn Quốc."],
  ["sweater", "n", "ˈswetɚ", "áo len", "My grandmother knitted this sweater for me.", "Bà tôi đã đan chiếc áo len này cho tôi."],
  ["suit", "n", "suːt", "bộ com-lê, bộ vest", "He wore a black suit to the wedding.", "Anh ấy mặc bộ vest đen đến đám cưới."],
  ["uniform", "n", "ˈjuːnəfɔːrm", "đồng phục", "Students must wear a uniform on Mondays.", "Học sinh phải mặc đồng phục vào thứ Hai."],
  ["socks", "n", "sɑːks", "tất, vớ", "I can't find a matching pair of socks.", "Tôi không tìm được đôi tất nào cùng màu."],
  ["shoes", "n", "ʃuːz", "giày", "Please take off your shoes at the door.", "Vui lòng cởi giày ở cửa."],
  ["sneakers", "n", "ˈsniːkɚz", "giày thể thao", "These sneakers are good for running.", "Đôi giày thể thao này rất hợp để chạy bộ."],
  ["sandals", "n", "ˈsændəlz", "dép quai hậu, xăng-đan", "I wear sandals when I go to the beach.", "Tôi đi xăng-đan khi ra biển."],
  ["boots", "n", "buːts", "giày bốt, ủng", "She bought a pair of black boots.", "Cô ấy đã mua một đôi bốt đen."],
  ["hat", "n", "hæt", "mũ, nón", "Wear a hat to protect yourself from the sun.", "Đội mũ để tránh nắng nhé."],
  ["cap", "n", "kæp", "mũ lưỡi trai", "He always wears a baseball cap.", "Anh ấy lúc nào cũng đội mũ lưỡi trai."],
  ["scarf", "n", "skɑːrf", "khăn quàng cổ", "She put on a scarf because it was windy.", "Cô ấy quàng khăn vì trời có gió."],
  ["gloves", "n", "ɡlʌvz", "găng tay", "I wear gloves when I ride my motorbike.", "Tôi đeo găng tay khi đi xe máy."],
  ["belt", "n", "belt", "thắt lưng", "These pants need a belt.", "Cái quần này cần thắt lưng."],
  ["tie", "n", "taɪ", "cà vạt", "Do I have to wear a tie to the interview?", "Tôi có phải đeo cà vạt khi đi phỏng vấn không?"],
  ["glasses", "n", "ˈɡlæsɪz", "kính mắt", "I can't read without my glasses.", "Tôi không đọc được nếu không có kính."],
  ["sunglasses", "n", "ˈsʌnɡlæsɪz", "kính râm", "Don't forget your sunglasses at the beach.", "Đừng quên kính râm khi ra biển nhé."],
  ["necklace", "n", "ˈnekləs", "vòng cổ, dây chuyền", "He gave her a gold necklace.", "Anh ấy tặng cô ấy một sợi dây chuyền vàng."],
  ["earrings", "n", "ˈɪrɪŋz", "bông tai, khuyên tai", "Those earrings look nice on you.", "Đôi bông tai đó trông hợp với bạn."],
  ["ring", "n", "rɪŋ", "nhẫn", "She wears her wedding ring every day.", "Cô ấy đeo nhẫn cưới mỗi ngày."],
  ["watch", "n", "wɑːtʃ", "đồng hồ đeo tay", "My watch is five minutes fast.", "Đồng hồ của tôi chạy nhanh năm phút."],
  ["handbag", "n", "ˈhændbæɡ", "túi xách", "She left her handbag in the taxi.", "Cô ấy để quên túi xách trên taxi."],
  ["wear", "v", "wer", "mặc, đeo, đội", "What are you going to wear tonight?", "Tối nay bạn định mặc gì?"],
  ["put on", "phr", "pʊt ˈɑːn", "mặc vào, đeo vào", "Put on your jacket before you go out.", "Mặc áo khoác vào trước khi ra ngoài."],
  ["take off", "phr", "teɪk ˈɑːf", "cởi ra", "He took off his hat and sat down.", "Anh ấy cởi mũ ra và ngồi xuống."],
  ["fit", "v", "fɪt", "vừa (kích cỡ)", "These shoes don't fit me anymore.", "Đôi giày này không còn vừa với tôi nữa."],
  ["tight", "adj", "taɪt", "chật, bó", "This shirt is too tight around my arms.", "Chiếc áo này quá chật ở phần tay."],
  ["loose", "adj", "luːs", "rộng, lỏng", "I like wearing loose clothes in summer.", "Tôi thích mặc quần áo rộng vào mùa hè."],
  ["fashionable", "adj", "ˈfæʃənəbəl", "hợp thời trang", "She always looks fashionable.", "Cô ấy lúc nào trông cũng hợp thời trang."],
  ["handsome", "adj", "ˈhænsəm", "đẹp trai", "Her boyfriend is tall and handsome.", "Bạn trai cô ấy cao và đẹp trai."],
  ["slim", "adj", "slɪm", "thon thả, mảnh mai", "She is slim because she exercises a lot.", "Cô ấy thon thả vì tập thể dục nhiều."],
  ["curly", "adj", "ˈkɝːli", "xoăn (tóc)", "My brother has short curly hair.", "Anh trai tôi có mái tóc ngắn xoăn."],
]);
