// Bộ từ mở rộng A: people, food, shopping, work, travel, school.
extendTopic("people", "Gia đình & mọi người", [
  ["sibling", "n", "ˈsɪblɪŋ", "anh chị em ruột", "I have two siblings.", "Tôi có hai anh chị em ruột."],
  ["grandfather", "n", "ˈɡrænfɑːðɚ", "ông", "My grandfather is eighty years old.", "Ông tôi đã tám mươi tuổi."],
  ["uncle", "n", "ˈʌŋkəl", "chú, bác, cậu", "My uncle has a pho restaurant in Hanoi.", "Chú tôi có một quán phở ở Hà Nội."],
  ["aunt", "n", "ænt", "cô, dì, bác gái", "My aunt lives near my house.", "Dì tôi sống gần nhà tôi."],
  ["nephew", "n", "ˈnefjuː", "cháu trai (con của anh chị em)", "My nephew is starting school this year.", "Cháu trai tôi năm nay bắt đầu đi học."],
  ["niece", "n", "niːs", "cháu gái (con của anh chị em)", "I bought a doll for my niece.", "Tôi mua một con búp bê cho cháu gái."],
  ["son", "n", "sʌn", "con trai", "Their son is learning to ride a bike.", "Con trai họ đang tập đi xe đạp."],
  ["twins", "n", "twɪnz", "cặp song sinh", "The twins look exactly the same.", "Cặp song sinh trông giống hệt nhau."],
  ["only child", "n", "ˌoʊnli ˈtʃaɪld", "con một", "I'm an only child.", "Tôi là con một."],
  ["teenager", "n", "ˈtiːneɪdʒɚ", "thiếu niên, tuổi mới lớn", "Many teenagers spend hours on their phones.", "Nhiều thiếu niên dành hàng giờ cho điện thoại."],
  ["adult", "n", "əˈdʌlt", "người lớn", "Tickets cost more for adults than for children.", "Vé người lớn đắt hơn vé trẻ em."],
  ["close friend", "n", "ˌkloʊs ˈfrend", "bạn thân", "She is my close friend from high school.", "Cô ấy là bạn thân của tôi từ hồi cấp ba."],
  ["stranger", "n", "ˈstreɪndʒɚ", "người lạ", "Don't open the door to strangers.", "Đừng mở cửa cho người lạ."],
  ["guest", "n", "ɡest", "khách", "We have guests for dinner tonight.", "Tối nay nhà tôi có khách đến ăn cơm."],
  ["couple", "n", "ˈkʌpəl", "cặp đôi, vợ chồng", "A young couple moved in next door.", "Một cặp vợ chồng trẻ mới chuyển đến nhà bên."],
  ["married", "adj", "ˈmerid", "đã kết hôn", "Are you married?", "Bạn đã lập gia đình chưa?"],
  ["single", "adj", "ˈsɪŋɡəl", "độc thân", "My brother is still single.", "Anh trai tôi vẫn còn độc thân."],
  ["wedding", "n", "ˈwedɪŋ", "đám cưới", "We went to my cousin's wedding last week.", "Tuần trước chúng tôi đi đám cưới em họ."],
  ["get married", "phr", "ɡet ˈmerid", "kết hôn, cưới", "They got married in 2020.", "Họ cưới nhau năm 2020."],
  ["divorced", "adj", "dɪˈvɔːrst", "đã ly hôn", "His parents are divorced.", "Bố mẹ anh ấy đã ly hôn."],
  ["grow up", "phr", "ɡroʊ ˈʌp", "lớn lên", "I grew up in a small village.", "Tôi lớn lên ở một ngôi làng nhỏ."],
  ["take after", "phr", "teɪk ˈæftɚ", "giống (bố, mẹ, người thân)", "She takes after her mother.", "Cô ấy giống mẹ."],
  ["look like", "phr", "ˈlʊk laɪk", "trông giống", "You look like your father.", "Bạn trông giống bố bạn."],
  ["in-laws", "n", "ˈɪnlɑːz", "nhà chồng, nhà vợ", "We spend Tet with my in-laws.", "Chúng tôi ăn Tết bên nhà chồng."],
  ["generation", "n", "ˌdʒenəˈreɪʃən", "thế hệ", "Three generations live in this house.", "Ba thế hệ sống trong ngôi nhà này."],
  ["ancestor", "n", "ˈænsestɚ", "tổ tiên", "We pray to our ancestors during Tet.", "Chúng tôi cúng tổ tiên dịp Tết."],
  ["childhood", "n", "ˈtʃaɪldhʊd", "tuổi thơ", "I had a happy childhood.", "Tôi đã có một tuổi thơ hạnh phúc."],
  ["introduce", "v", "ˌɪntrəˈduːs", "giới thiệu", "Let me introduce you to my wife.", "Để tôi giới thiệu bạn với vợ tôi."],
]);

extendTopic("food", "Ăn uống", [
  ["lunch", "n", "lʌntʃ", "bữa trưa", "Let's have lunch together.", "Mình ăn trưa cùng nhau nhé."],
  ["dinner", "n", "ˈdɪnɚ", "bữa tối", "We have dinner at seven.", "Nhà tôi ăn tối lúc bảy giờ."],
  ["rice", "n", "raɪs", "cơm, gạo", "Vietnamese people eat rice every day.", "Người Việt ăn cơm hằng ngày."],
  ["noodles", "n", "ˈnuːdəlz", "mì, bún, phở", "I had beef noodles for breakfast.", "Sáng nay tôi ăn phở bò."],
  ["pork", "n", "pɔːrk", "thịt lợn, thịt heo", "Grilled pork with rice is my favorite.", "Cơm sườn nướng là món tôi thích nhất."],
  ["beef", "n", "biːf", "thịt bò", "I don't eat beef.", "Tôi không ăn thịt bò."],
  ["seafood", "n", "ˈsiːfuːd", "hải sản", "The seafood in Nha Trang is very fresh.", "Hải sản ở Nha Trang rất tươi."],
  ["fruit", "n", "fruːt", "trái cây, hoa quả", "I eat fruit after every meal.", "Tôi ăn trái cây sau mỗi bữa."],
  ["salty", "adj", "ˈsɑːlti", "mặn", "The soup is a bit too salty.", "Canh hơi mặn quá."],
  ["sweet", "adj", "swiːt", "ngọt", "This coffee is too sweet for me.", "Cà phê này ngọt quá đối với tôi."],
  ["sour", "adj", "saʊɚ", "chua", "Green mangoes are very sour.", "Xoài xanh rất chua."],
  ["bitter", "adj", "ˈbɪtɚ", "đắng", "Black coffee tastes bitter.", "Cà phê đen có vị đắng."],
  ["full", "adj", "fʊl", "no", "No more, thanks. I'm full.", "Thôi, cảm ơn. Tôi no rồi."],
  ["thirsty", "adj", "ˈθɝːsti", "khát", "I'm thirsty. Can I have some water?", "Tôi khát quá. Cho tôi xin ít nước nhé?"],
  ["snack", "n", "snæk", "đồ ăn vặt", "I usually have a snack in the afternoon.", "Buổi chiều tôi thường ăn vặt."],
  ["dessert", "n", "dɪˈzɝːt", "món tráng miệng", "What would you like for dessert?", "Bạn muốn ăn gì tráng miệng?"],
  ["grill", "v", "ɡrɪl", "nướng", "My dad likes to grill fish on weekends.", "Bố tôi thích nướng cá vào cuối tuần."],
  ["taste", "v", "teɪst", "nếm; có vị", "Taste the soup and add some salt.", "Nếm canh rồi thêm chút muối."],
  ["ingredient", "n", "ɪnˈɡriːdiənt", "nguyên liệu", "What ingredients do we need for this dish?", "Món này cần những nguyên liệu gì?"],
  ["vegetarian", "adj", "ˌvedʒəˈteriən", "ăn chay", "Do you have any vegetarian dishes?", "Quán có món chay nào không?"],
  ["bowl", "n", "boʊl", "cái bát, cái tô", "I'd like a big bowl of pho.", "Cho tôi một tô phở lớn."],
  ["chopsticks", "n", "ˈtʃɑːpstɪks", "đũa", "Can you use chopsticks?", "Bạn có biết dùng đũa không?"],
  ["street food", "n", "ˌstriːt ˈfuːd", "đồ ăn đường phố", "Hanoi is famous for its street food.", "Hà Nội nổi tiếng với đồ ăn đường phố."],
  ["fish sauce", "n", "ˈfɪʃ sɑːs", "nước mắm", "Add a little fish sauce to the soup.", "Cho một chút nước mắm vào canh."],
  ["stir-fry", "v", "ˈstɝːfraɪ", "xào", "Stir-fry the vegetables with garlic.", "Xào rau với tỏi."],
  ["leftovers", "n", "ˈleftoʊvɚz", "đồ ăn thừa", "We had leftovers for lunch.", "Chúng tôi ăn đồ thừa vào bữa trưa."],
  ["fresh", "adj", "freʃ", "tươi", "I buy fresh vegetables at the market.", "Tôi mua rau tươi ở chợ."],
  ["eat out", "phr", "iːt ˈaʊt", "ăn ngoài, ăn tiệm", "We eat out every Friday night.", "Tối thứ Sáu nào nhà tôi cũng ăn ngoài."],
]);

extendTopic("shopping", "Mua sắm & tiền bạc", [
  ["customer", "n", "ˈkʌstəmɚ", "khách hàng", "The shop has a lot of customers today.", "Hôm nay cửa hàng đông khách."],
  ["on sale", "phr", "ɑːn ˈseɪl", "đang giảm giá", "These shoes are on sale this week.", "Tuần này đôi giày này đang giảm giá."],
  ["bargain", "n", "ˈbɑːrɡən", "món hời", "This bag was a real bargain.", "Cái túi này đúng là một món hời."],
  ["haggle", "v", "ˈhæɡəl", "mặc cả, trả giá", "You can haggle at Ben Thanh Market.", "Bạn có thể mặc cả ở chợ Bến Thành."],
  ["cost", "v", "kɑːst", "có giá, tốn", "How much does this cost?", "Cái này giá bao nhiêu?"],
  ["pay", "v", "peɪ", "trả tiền", "Can I pay by card?", "Tôi trả bằng thẻ được không?"],
  ["refund", "n", "ˈriːfʌnd", "tiền hoàn lại", "I'd like a refund, please.", "Tôi muốn được hoàn tiền."],
  ["return", "v", "rɪˈtɝːn", "trả lại (hàng)", "Can I return this if it doesn't fit?", "Nếu không vừa thì tôi trả lại được không?"],
  ["exchange", "v", "ɪksˈtʃeɪndʒ", "đổi (hàng, tiền)", "Can I exchange this for a bigger size?", "Tôi đổi cái này lấy cỡ lớn hơn được không?"],
  ["credit card", "n", "ˈkredɪt ˌkɑːrd", "thẻ tín dụng", "Do you accept credit cards?", "Ở đây có nhận thẻ tín dụng không?"],
  ["wallet", "n", "ˈwɑːlɪt", "cái ví", "I left my wallet at home.", "Tôi để quên ví ở nhà."],
  ["coin", "n", "kɔɪn", "đồng xu", "I have some coins in my pocket.", "Tôi có vài đồng xu trong túi."],
  ["budget", "n", "ˈbʌdʒɪt", "ngân sách, khoản chi dự tính", "What is your budget for a new laptop?", "Bạn định chi bao nhiêu cho máy tính mới?"],
  ["borrow", "v", "ˈbɑːroʊ", "mượn, vay", "Can I borrow some money?", "Mình mượn ít tiền được không?"],
  ["lend", "v", "lend", "cho mượn, cho vay", "Could you lend me 100,000 dong?", "Bạn cho mình mượn 100.000 đồng được không?"],
  ["owe", "v", "oʊ", "nợ", "I still owe you for lunch.", "Mình vẫn còn nợ bạn tiền bữa trưa."],
  ["debt", "n", "det", "khoản nợ", "He is trying to pay off his debt.", "Anh ấy đang cố trả hết nợ."],
  ["waste", "v", "weɪst", "lãng phí", "Don't waste money on things you don't need.", "Đừng lãng phí tiền vào những thứ không cần."],
  ["shop around", "phr", "ʃɑːp əˈraʊnd", "đi xem nhiều nơi để so giá", "Shop around before you buy a phone.", "Hãy so giá nhiều nơi trước khi mua điện thoại."],
  ["window-shopping", "n", "ˈwɪndoʊ ˌʃɑːpɪŋ", "việc đi ngắm hàng (không mua)", "We went window-shopping at the mall.", "Chúng tôi đi ngắm hàng ở trung tâm thương mại."],
  ["cart", "n", "kɑːrt", "xe đẩy, giỏ hàng", "I added three items to my cart.", "Tôi đã thêm ba món vào giỏ hàng."],
  ["checkout", "n", "ˈtʃekaʊt", "quầy thanh toán", "Please pay at the checkout.", "Vui lòng thanh toán ở quầy thu ngân."],
  ["delivery", "n", "dɪˈlɪvɚi", "sự giao hàng", "Delivery is free for orders over 200,000 dong.", "Miễn phí giao hàng cho đơn trên 200.000 đồng."],
  ["free", "adj", "friː", "miễn phí", "The second drink is free.", "Ly thứ hai được miễn phí."],
  ["worth", "adj", "wɝːθ", "đáng giá", "This jacket is worth the money.", "Cái áo khoác này đáng đồng tiền."],
  ["quality", "n", "ˈkwɑːləti", "chất lượng", "The quality of this bag is very good.", "Chất lượng cái túi này rất tốt."],
  ["brand", "n", "brænd", "thương hiệu", "Which brand of phone do you use?", "Bạn dùng điện thoại hãng nào?"],
  ["out of stock", "phr", "ˌaʊt əv ˈstɑːk", "hết hàng", "Sorry, this item is out of stock.", "Xin lỗi, món này hết hàng rồi."],
]);

extendTopic("work", "Công việc", [
  ["office", "n", "ˈɑːfɪs", "văn phòng", "I get to the office at eight.", "Tôi đến văn phòng lúc tám giờ."],
  ["employee", "n", "ɪmˈplɔɪiː", "nhân viên", "The company has about 50 employees.", "Công ty có khoảng 50 nhân viên."],
  ["employer", "n", "ɪmˈplɔɪɚ", "người sử dụng lao động, chủ", "My employer pays for my English classes.", "Công ty trả tiền học tiếng Anh cho tôi."],
  ["staff", "n", "stæf", "nhân viên (nói chung)", "All staff must attend the meeting.", "Toàn bộ nhân viên phải dự cuộc họp."],
  ["team", "n", "tiːm", "nhóm, đội", "Our team finished the project early.", "Nhóm chúng tôi hoàn thành dự án sớm."],
  ["project", "n", "ˈprɑːdʒekt", "dự án", "I'm working on a new project.", "Tôi đang làm một dự án mới."],
  ["task", "n", "tæsk", "nhiệm vụ, việc cần làm", "I have many tasks to finish today.", "Hôm nay tôi có nhiều việc phải làm xong."],
  ["report", "n", "rɪˈpɔːrt", "bản báo cáo", "I need to send the report by Friday.", "Tôi phải gửi báo cáo trước thứ Sáu."],
  ["contract", "n", "ˈkɑːntrækt", "hợp đồng", "Please read the contract before you sign.", "Hãy đọc hợp đồng trước khi ký."],
  ["hire", "v", "haɪɚ", "thuê, tuyển dụng", "The company is hiring new staff.", "Công ty đang tuyển thêm nhân viên."],
  ["fire", "v", "faɪɚ", "sa thải, đuổi việc", "He was fired for being late every day.", "Anh ấy bị đuổi việc vì ngày nào cũng đi muộn."],
  ["quit", "v", "kwɪt", "bỏ (việc)", "She quit her job to start a business.", "Cô ấy nghỉ việc để khởi nghiệp."],
  ["promotion", "n", "prəˈmoʊʃən", "sự thăng chức", "He got a promotion last year.", "Năm ngoái anh ấy được thăng chức."],
  ["resume", "n", "ˈrezəmeɪ", "sơ yếu lý lịch, CV", "Send your resume to this email address.", "Hãy gửi CV của bạn đến địa chỉ email này."],
  ["full-time", "adj", "ˌfʊlˈtaɪm", "toàn thời gian", "I'm looking for a full-time job.", "Tôi đang tìm một công việc toàn thời gian."],
  ["part-time", "adj", "ˌpɑːrtˈtaɪm", "bán thời gian", "Many students have part-time jobs.", "Nhiều sinh viên làm thêm bán thời gian."],
  ["shift", "n", "ʃɪft", "ca làm việc", "I work the night shift this week.", "Tuần này tôi làm ca đêm."],
  ["day off", "n", "ˌdeɪ ˈɑːf", "ngày nghỉ", "Tomorrow is my day off.", "Mai là ngày nghỉ của tôi."],
  ["work from home", "phr", "ˌwɝːk frəm ˈhoʊm", "làm việc tại nhà", "I work from home on Mondays.", "Thứ Hai tôi làm việc ở nhà."],
  ["commute", "v", "kəˈmjuːt", "đi lại (giữa nhà và chỗ làm)", "I commute to work by motorbike.", "Tôi đi làm bằng xe máy."],
  ["company", "n", "ˈkʌmpəni", "công ty", "She works for a big company in Saigon.", "Cô ấy làm cho một công ty lớn ở Sài Gòn."],
  ["client", "n", "ˈklaɪənt", "khách hàng (của công ty)", "I have a meeting with a client at ten.", "Tôi có cuộc họp với khách hàng lúc mười giờ."],
  ["responsible", "adj", "rɪˈspɑːnsəbəl", "có trách nhiệm, chịu trách nhiệm", "Who is responsible for this project?", "Ai chịu trách nhiệm dự án này?"],
  ["hardworking", "adj", "ˌhɑːrdˈwɝːkɪŋ", "chăm chỉ", "She is a hardworking employee.", "Cô ấy là một nhân viên chăm chỉ."],
  ["earn", "v", "ɝːn", "kiếm (tiền)", "How much do you earn a month?", "Mỗi tháng bạn kiếm được bao nhiêu?"],
  ["retire", "v", "rɪˈtaɪɚ", "nghỉ hưu", "My father retired last year.", "Bố tôi nghỉ hưu năm ngoái."],
  ["unemployed", "adj", "ˌʌnɪmˈplɔɪd", "thất nghiệp", "He has been unemployed for three months.", "Anh ấy thất nghiệp đã ba tháng."],
  ["in charge of", "phr", "ɪn ˈtʃɑːrdʒ əv", "phụ trách", "Who is in charge of marketing?", "Ai phụ trách mảng marketing?"],
]);

extendTopic("travel", "Du lịch & đi lại", [
  ["airport", "n", "ˈerpɔːrt", "sân bay", "We got to the airport two hours early.", "Chúng tôi đến sân bay sớm hai tiếng."],
  ["check in", "phr", "tʃek ˈɪn", "làm thủ tục (khách sạn, sân bay)", "You can check in after 2 p.m.", "Quý khách có thể nhận phòng sau 2 giờ chiều."],
  ["check out", "phr", "tʃek ˈaʊt", "trả phòng", "We have to check out by noon.", "Chúng tôi phải trả phòng trước 12 giờ trưa."],
  ["trip", "n", "trɪp", "chuyến đi", "How was your trip to Sa Pa?", "Chuyến đi Sa Pa của bạn thế nào?"],
  ["abroad", "adv", "əˈbrɑːd", "ở nước ngoài, ra nước ngoài", "I have never traveled abroad.", "Tôi chưa bao giờ đi nước ngoài."],
  ["tourist", "n", "ˈtʊrɪst", "khách du lịch", "Hoi An is full of tourists in summer.", "Mùa hè Hội An đông khách du lịch."],
  ["visa", "n", "ˈviːzə", "thị thực, visa", "Do I need a visa to visit Japan?", "Tôi có cần visa để đi Nhật không?"],
  ["suitcase", "n", "ˈsuːtkeɪs", "va li", "My suitcase is too heavy.", "Va li của tôi nặng quá."],
  ["backpack", "n", "ˈbækpæk", "ba lô", "I only take a backpack when I travel.", "Khi đi du lịch tôi chỉ mang một cái ba lô."],
  ["reservation", "n", "ˌrezɚˈveɪʃən", "sự đặt chỗ trước", "I have a reservation under the name Lan.", "Tôi đã đặt chỗ trước với tên Lan."],
  ["delayed", "adj", "dɪˈleɪd", "bị hoãn, bị trễ", "The train is delayed because of the rain.", "Tàu bị trễ vì trời mưa."],
  ["cancel", "v", "ˈkænsəl", "hủy", "Our flight was canceled.", "Chuyến bay của chúng tôi bị hủy."],
  ["departure", "n", "dɪˈpɑːrtʃɚ", "sự khởi hành, giờ đi", "What time is the departure?", "Mấy giờ khởi hành?"],
  ["arrival", "n", "əˈraɪvəl", "sự đến nơi, giờ đến", "Please call me on arrival.", "Đến nơi thì gọi cho tôi nhé."],
  ["boarding pass", "n", "ˈbɔːrdɪŋ ˌpæs", "thẻ lên máy bay", "Please show your boarding pass.", "Vui lòng xuất trình thẻ lên máy bay."],
  ["round-trip", "adj", "ˌraʊndˈtrɪp", "khứ hồi", "A round-trip ticket is cheaper.", "Vé khứ hồi rẻ hơn."],
  ["one-way", "adj", "ˌwʌnˈweɪ", "một chiều", "I'd like a one-way ticket to Da Nang.", "Tôi muốn mua một vé một chiều đi Đà Nẵng."],
  ["motorbike", "n", "ˈmoʊtɚbaɪk", "xe máy", "Most people in Hanoi ride motorbikes.", "Phần lớn người Hà Nội đi xe máy."],
  ["get lost", "phr", "ɡet ˈlɑːst", "bị lạc", "We got lost in the Old Quarter.", "Chúng tôi bị lạc ở phố cổ."],
  ["directions", "n", "dɪˈrekʃənz", "sự chỉ đường", "Can you give me directions to the station?", "Bạn chỉ đường cho tôi đến ga được không?"],
  ["go straight", "phr", "ɡoʊ ˈstreɪt", "đi thẳng", "Go straight for about 200 meters.", "Đi thẳng khoảng 200 mét."],
  ["cross", "v", "krɑːs", "băng qua (đường)", "Be careful when you cross the street.", "Cẩn thận khi sang đường nhé."],
  ["pick up", "phr", "pɪk ˈʌp", "đón (ai đó)", "I'll pick you up at the airport.", "Tôi sẽ đón bạn ở sân bay."],
  ["sleeper bus", "n", "ˈsliːpɚ ˌbʌs", "xe khách giường nằm", "We took a sleeper bus to Da Lat.", "Chúng tôi đi xe giường nằm lên Đà Lạt."],
  ["accommodation", "n", "əˌkɑːməˈdeɪʃən", "chỗ ở", "Accommodation in Phu Quoc is not cheap.", "Chỗ ở tại Phú Quốc không rẻ."],
  ["explore", "v", "ɪkˈsplɔːr", "khám phá", "We spent a day exploring Hue.", "Chúng tôi dành một ngày khám phá Huế."],
  ["pack", "v", "pæk", "đóng gói, xếp đồ (vào va li)", "Have you packed your bags yet?", "Bạn xếp đồ vào va li chưa?"],
  ["vacation", "n", "veɪˈkeɪʃən", "kỳ nghỉ", "We're going on vacation next week.", "Tuần sau chúng tôi đi nghỉ."],
]);

extendTopic("school", "Trường học & học tập", [
  ["classroom", "n", "ˈklæsruːm", "lớp học, phòng học", "Our classroom is on the second floor.", "Phòng học của chúng tôi ở tầng hai."],
  ["lesson", "n", "ˈlesən", "bài học, buổi học", "Today's lesson is about the past tense.", "Bài học hôm nay là về thì quá khứ."],
  ["homework", "n", "ˈhoʊmwɝːk", "bài tập về nhà", "Have you finished your homework?", "Con làm xong bài tập về nhà chưa?"],
  ["exam", "n", "ɪɡˈzæm", "kỳ thi, bài thi", "I have an English exam tomorrow.", "Mai tôi có bài thi tiếng Anh."],
  ["grade", "n", "ɡreɪd", "điểm số", "She got good grades this semester.", "Học kỳ này cô ấy được điểm cao."],
  ["pass", "v", "pæs", "thi đỗ, qua", "I hope I pass the test.", "Mong là mình thi qua."],
  ["fail", "v", "feɪl", "thi trượt, không đạt", "He failed his driving test.", "Anh ấy thi trượt bằng lái xe."],
  ["subject", "n", "ˈsʌbdʒekt", "môn học", "What's your favorite subject?", "Bạn thích môn học nào nhất?"],
  ["math", "n", "mæθ", "môn toán", "I'm not very good at math.", "Tôi học toán không giỏi lắm."],
  ["history", "n", "ˈhɪstɚi", "lịch sử", "We learn Vietnamese history at school.", "Ở trường chúng tôi học lịch sử Việt Nam."],
  ["literature", "n", "ˈlɪtɚətʃɚ", "văn học, môn văn", "She loves reading literature.", "Cô ấy rất thích đọc văn học."],
  ["physics", "n", "ˈfɪzɪks", "vật lý", "Physics was my hardest subject.", "Vật lý là môn khó nhất với tôi."],
  ["chemistry", "n", "ˈkeməstri", "hóa học", "We have a chemistry test on Monday.", "Thứ Hai chúng tôi có bài kiểm tra hóa."],
  ["textbook", "n", "ˈtekstbʊk", "sách giáo khoa", "Open your textbooks to page 20.", "Các em mở sách giáo khoa trang 20."],
  ["dictionary", "n", "ˈdɪkʃəneri", "từ điển", "Look up the word in the dictionary.", "Tra từ đó trong từ điển."],
  ["semester", "n", "səˈmestɚ", "học kỳ", "The new semester starts in September.", "Học kỳ mới bắt đầu vào tháng Chín."],
  ["university", "n", "ˌjuːnəˈvɝːsəti", "trường đại học", "My sister studies at a university in Hanoi.", "Chị tôi học đại học ở Hà Nội."],
  ["degree", "n", "dɪˈɡriː", "bằng cấp (đại học)", "He has a degree in economics.", "Anh ấy có bằng kinh tế."],
  ["scholarship", "n", "ˈskɑːlɚʃɪp", "học bổng", "She won a scholarship to study in Japan.", "Cô ấy giành được học bổng du học Nhật Bản."],
  ["classmate", "n", "ˈklæsmeɪt", "bạn cùng lớp", "My classmates are very helpful.", "Các bạn cùng lớp rất hay giúp đỡ tôi."],
  ["tuition", "n", "tuːˈɪʃən", "học phí", "Tuition at private schools is very high.", "Học phí trường tư rất cao."],
  ["memorize", "v", "ˈmeməraɪz", "học thuộc, ghi nhớ", "I memorize ten new words every day.", "Mỗi ngày tôi học thuộc mười từ mới."],
  ["review", "v", "rɪˈvjuː", "ôn tập", "Let's review the lesson before the test.", "Mình ôn lại bài trước khi kiểm tra nhé."],
  ["take notes", "phr", "teɪk ˈnoʊts", "ghi chép", "Take notes during the lecture.", "Hãy ghi chép trong giờ giảng."],
  ["hand in", "phr", "hænd ˈɪn", "nộp (bài)", "Please hand in your essays on Friday.", "Các em nộp bài luận vào thứ Sáu nhé."],
  ["absent", "adj", "ˈæbsənt", "vắng mặt", "Three students were absent today.", "Hôm nay có ba học sinh vắng mặt."],
  ["attend", "v", "əˈtend", "tham dự, đi học", "I attend English classes twice a week.", "Tôi đi học tiếng Anh hai buổi một tuần."],
  ["explain", "v", "ɪkˈspleɪn", "giải thích", "Could you explain this word again?", "Thầy giải thích lại từ này được không ạ?"],
  ["mistake", "n", "mɪˈsteɪk", "lỗi, sai sót", "Don't be afraid of making mistakes.", "Đừng sợ mắc lỗi."],
  ["essay", "n", "ˈeseɪ", "bài luận", "I have to write an essay about my hometown.", "Tôi phải viết một bài luận về quê mình."],
  ["presentation", "n", "ˌprezənˈteɪʃən", "bài thuyết trình", "I'm nervous about my presentation tomorrow.", "Tôi hồi hộp về bài thuyết trình ngày mai."],
  ["graduate", "v", "ˈɡrædʒueɪt", "tốt nghiệp", "She graduated from university last year.", "Cô ấy tốt nghiệp đại học năm ngoái."],
  ["cheat", "v", "tʃiːt", "gian lận, quay cóp", "Never cheat in an exam.", "Đừng bao giờ quay cóp khi thi."],
  ["knowledge", "n", "ˈnɑːlɪdʒ", "kiến thức", "Reading helps you gain knowledge.", "Đọc sách giúp bạn có thêm kiến thức."],
  ["improve", "v", "ɪmˈpruːv", "cải thiện, tiến bộ", "I want to improve my English.", "Tôi muốn cải thiện tiếng Anh."],
  ["pronunciation", "n", "prəˌnʌnsiˈeɪʃən", "cách phát âm", "Your pronunciation is getting better.", "Phát âm của bạn đang tiến bộ."],
  ["vocabulary", "n", "voʊˈkæbjəleri", "từ vựng", "Reading is a good way to learn vocabulary.", "Đọc là một cách hay để học từ vựng."],
  ["grammar", "n", "ˈɡræmɚ", "ngữ pháp", "English grammar is not too difficult.", "Ngữ pháp tiếng Anh không quá khó."],
  ["fluent", "adj", "ˈfluːənt", "trôi chảy, lưu loát", "He speaks fluent English.", "Anh ấy nói tiếng Anh lưu loát."],
  ["course", "n", "kɔːrs", "khóa học", "I signed up for an online English course.", "Tôi đã đăng ký một khóa học tiếng Anh trực tuyến."],
]);
