// Bộ từ bổ sung B: nhà cửa, sức khỏe, cảm xúc, công nghệ, thời gian, sở thích.
extendTopic("home", "Nhà cửa & sinh hoạt", [
  ["kitchen", "n", "ˈkɪtʃən", "nhà bếp", "Mom is cooking in the kitchen.", "Mẹ đang nấu ăn trong bếp."],
  ["bedroom", "n", "ˈbedruːm", "phòng ngủ", "My bedroom is small but cozy.", "Phòng ngủ của tôi nhỏ nhưng ấm cúng."],
  ["bathroom", "n", "ˈbæθruːm", "phòng tắm", "The bathroom is next to the kitchen.", "Phòng tắm ở cạnh nhà bếp."],
  ["living room", "n", "ˈlɪvɪŋ ruːm", "phòng khách", "We watch TV in the living room.", "Chúng tôi xem tivi trong phòng khách."],
  ["balcony", "n", "ˈbælkəni", "ban công", "She grows flowers on the balcony.", "Cô ấy trồng hoa ngoài ban công."],
  ["stairs", "n", "sterz", "cầu thang", "Be careful on the stairs.", "Cẩn thận khi đi cầu thang nhé."],
  ["fridge", "n", "frɪdʒ", "tủ lạnh", "Put the milk back in the fridge.", "Cất sữa lại vào tủ lạnh đi."],
  ["stove", "n", "stoʊv", "bếp nấu", "Don't forget to turn off the stove.", "Đừng quên tắt bếp nhé."],
  ["sink", "n", "sɪŋk", "bồn rửa", "The dirty dishes are in the sink.", "Bát đĩa bẩn ở trong bồn rửa."],
  ["sofa", "n", "ˈsoʊfə", "ghế sofa", "Dad fell asleep on the sofa.", "Bố ngủ quên trên ghế sofa."],
  ["pillow", "n", "ˈpɪloʊ", "cái gối", "I need a softer pillow.", "Tôi cần một cái gối mềm hơn."],
  ["blanket", "n", "ˈblæŋkɪt", "chăn, mền", "It's cold, so take a blanket.", "Trời lạnh, lấy chăn đắp đi."],
  ["mirror", "n", "ˈmɪrɚ", "cái gương", "She looked in the mirror before leaving.", "Cô ấy soi gương trước khi ra ngoài."],
  ["towel", "n", "ˈtaʊəl", "khăn tắm", "Can I borrow a clean towel?", "Cho tôi mượn một cái khăn sạch được không?"],
  ["shelf", "n", "ʃelf", "cái kệ, giá", "The books are on the top shelf.", "Sách ở trên kệ trên cùng."],
  ["drawer", "n", "drɔːr", "ngăn kéo", "The keys are in the top drawer.", "Chìa khóa ở trong ngăn kéo trên cùng."],
  ["ceiling fan", "n", "ˈsiːlɪŋ fæn", "quạt trần", "Please turn on the ceiling fan.", "Làm ơn bật quạt trần lên."],
  ["air conditioner", "n", "ˈer kənˌdɪʃənɚ", "máy điều hòa", "The air conditioner is too cold.", "Máy điều hòa lạnh quá."],
  ["washing machine", "n", "ˈwɑːʃɪŋ məˌʃiːn", "máy giặt", "The washing machine is broken again.", "Máy giặt lại hỏng rồi."],
  ["sweep", "v", "swiːp", "quét", "I sweep the floor every morning.", "Sáng nào tôi cũng quét nhà."],
  ["mop", "v", "mɑːp", "lau (sàn)", "Can you mop the kitchen floor?", "Bạn lau sàn bếp giúp mình được không?"],
  ["iron", "v", "ˈaɪɚn", "là, ủi (quần áo)", "I need to iron my shirt tonight.", "Tối nay tôi phải ủi áo sơ mi."],
  ["wash the dishes", "phr", "wɑːʃ ðə ˈdɪʃɪz", "rửa bát", "It's your turn to wash the dishes.", "Đến lượt bạn rửa bát rồi."],
  ["make the bed", "phr", "meɪk ðə bed", "dọn giường", "I make the bed after I get up.", "Tôi dọn giường sau khi thức dậy."],
  ["take out the trash", "phr", "teɪk aʊt ðə træʃ", "đổ rác", "Please take out the trash tonight.", "Tối nay nhớ đổ rác nhé."],
  ["take a shower", "phr", "teɪk ə ˈʃaʊɚ", "tắm (vòi sen)", "I take a shower before bed.", "Tôi tắm trước khi đi ngủ."],
  ["get dressed", "phr", "ɡet drest", "mặc quần áo", "Get dressed quickly, we're late!", "Mặc đồ nhanh lên, mình trễ rồi!"],
  ["go to bed", "phr", "ɡoʊ tə bed", "đi ngủ", "I usually go to bed at eleven.", "Tôi thường đi ngủ lúc mười một giờ."],
]);

extendTopic("health", "Sức khỏe", [
  ["sick", "adj", "sɪk", "ốm, bệnh", "She's sick, so she stayed home today.", "Cô ấy bị ốm nên hôm nay ở nhà."],
  ["catch a cold", "phr", "kætʃ ə koʊld", "bị cảm lạnh", "Wear a jacket or you'll catch a cold.", "Mặc áo khoác vào kẻo bị cảm lạnh."],
  ["flu", "n", "fluː", "bệnh cúm", "Many students have the flu this week.", "Tuần này nhiều học sinh bị cúm."],
  ["stomachache", "n", "ˈstʌməkeɪk", "đau bụng", "I have a stomachache after eating street food.", "Tôi bị đau bụng sau khi ăn đồ vỉa hè."],
  ["toothache", "n", "ˈtuːθeɪk", "đau răng", "I can't sleep because of my toothache.", "Tôi không ngủ được vì đau răng."],
  ["runny nose", "n", "ˌrʌni ˈnoʊz", "sổ mũi", "My son has a runny nose.", "Con trai tôi bị sổ mũi."],
  ["dizzy", "adj", "ˈdɪzi", "chóng mặt", "I feel dizzy when I stand up.", "Tôi thấy chóng mặt khi đứng dậy."],
  ["allergy", "n", "ˈælɚdʒi", "dị ứng", "I have an allergy to seafood.", "Tôi bị dị ứng hải sản."],
  ["pain", "n", "peɪn", "cơn đau", "I have a pain in my back.", "Tôi bị đau ở lưng."],
  ["injury", "n", "ˈɪndʒɚi", "chấn thương", "He missed the game because of an injury.", "Anh ấy lỡ trận đấu vì chấn thương."],
  ["hospital", "n", "ˈhɑːspɪtəl", "bệnh viện", "My grandfather is in the hospital.", "Ông tôi đang nằm viện."],
  ["clinic", "n", "ˈklɪnɪk", "phòng khám", "There's a small clinic near my house.", "Có một phòng khám nhỏ gần nhà tôi."],
  ["pharmacy", "n", "ˈfɑːrməsi", "hiệu thuốc", "You can buy it at any pharmacy.", "Bạn có thể mua nó ở bất kỳ hiệu thuốc nào."],
  ["prescription", "n", "prɪˈskrɪpʃən", "đơn thuốc", "The doctor gave me a prescription.", "Bác sĩ kê cho tôi một đơn thuốc."],
  ["pill", "n", "pɪl", "viên thuốc", "Take one pill after each meal.", "Uống một viên sau mỗi bữa ăn."],
  ["symptom", "n", "ˈsɪmptəm", "triệu chứng", "What are your symptoms?", "Bạn có những triệu chứng gì?"],
  ["temperature", "n", "ˈtemprətʃɚ", "nhiệt độ, thân nhiệt", "The nurse took my temperature.", "Y tá đo thân nhiệt cho tôi."],
  ["check-up", "n", "ˈtʃek ʌp", "khám sức khỏe tổng quát", "I go for a check-up every year.", "Năm nào tôi cũng đi khám sức khỏe."],
  ["injection", "n", "ɪnˈdʒekʃən", "mũi tiêm", "The baby cried after the injection.", "Em bé khóc sau khi bị tiêm."],
  ["surgery", "n", "ˈsɝːdʒɚi", "ca phẫu thuật", "She needs surgery on her knee.", "Cô ấy cần phẫu thuật đầu gối."],
  ["ambulance", "n", "ˈæmbjələns", "xe cứu thương", "Call an ambulance, quickly!", "Gọi xe cứu thương, nhanh lên!"],
  ["health insurance", "n", "ˈhelθ ɪnˌʃʊrəns", "bảo hiểm y tế", "Do you have health insurance?", "Bạn có bảo hiểm y tế không?"],
  ["infection", "n", "ɪnˈfekʃən", "sự nhiễm trùng", "Keep the cut clean to avoid infection.", "Giữ vết cắt sạch để tránh nhiễm trùng."],
  ["diet", "n", "ˈdaɪət", "chế độ ăn", "A healthy diet includes lots of vegetables.", "Chế độ ăn lành mạnh có nhiều rau."],
  ["overweight", "adj", "ˌoʊvɚˈweɪt", "thừa cân", "The doctor said I'm a little overweight.", "Bác sĩ nói tôi hơi thừa cân."],
  ["stay up late", "phr", "steɪ ʌp leɪt", "thức khuya", "Try not to stay up late every night.", "Cố đừng thức khuya mỗi đêm."],
  ["get enough sleep", "phr", "ɡet ɪˈnʌf sliːp", "ngủ đủ giấc", "Students often don't get enough sleep.", "Học sinh thường không ngủ đủ giấc."],
  ["quit smoking", "phr", "kwɪt ˈsmoʊkɪŋ", "bỏ thuốc lá", "My uncle quit smoking last year.", "Chú tôi đã bỏ thuốc lá năm ngoái."],
]);

extendTopic("feelings", "Cảm xúc & tính cách", [
  ["happy", "adj", "ˈhæpi", "vui vẻ, hạnh phúc", "I'm so happy to see you again.", "Mình rất vui được gặp lại bạn."],
  ["sad", "adj", "sæd", "buồn", "She felt sad when her friend moved away.", "Cô ấy buồn khi bạn mình chuyển đi."],
  ["angry", "adj", "ˈæŋɡri", "tức giận", "Dad was angry because I came home late.", "Bố giận vì tôi về nhà muộn."],
  ["scared", "adj", "skerd", "sợ hãi", "My little sister is scared of the dark.", "Em gái tôi sợ bóng tối."],
  ["surprised", "adj", "sɚˈpraɪzd", "ngạc nhiên", "I was surprised by the news.", "Tôi rất ngạc nhiên trước tin đó."],
  ["lonely", "adj", "ˈloʊnli", "cô đơn", "He feels lonely living in a big city.", "Anh ấy thấy cô đơn khi sống ở thành phố lớn."],
  ["relaxed", "adj", "rɪˈlækst", "thư giãn, thoải mái", "I feel relaxed after a hot shower.", "Tôi thấy thư giãn sau khi tắm nước nóng."],
  ["stressed", "adj", "strest", "căng thẳng", "She's stressed about her exams.", "Cô ấy căng thẳng vì kỳ thi."],
  ["disappointed", "adj", "ˌdɪsəˈpɔɪntɪd", "thất vọng", "We were disappointed with the result.", "Chúng tôi thất vọng với kết quả."],
  ["grateful", "adj", "ˈɡreɪtfəl", "biết ơn", "I'm grateful for your help.", "Tôi rất biết ơn sự giúp đỡ của bạn."],
  ["jealous", "adj", "ˈdʒeləs", "ghen tị", "He's jealous of his brother's new phone.", "Cậu ấy ghen tị với điện thoại mới của anh trai."],
  ["calm", "adj", "kɑːm", "bình tĩnh", "Stay calm and listen to me.", "Hãy bình tĩnh và nghe tôi nói."],
  ["annoyed", "adj", "əˈnɔɪd", "bực mình", "I get annoyed when people are late.", "Tôi bực mình khi người khác đến muộn."],
  ["confused", "adj", "kənˈfjuːzd", "bối rối, không hiểu", "I'm confused. Can you explain again?", "Mình chưa hiểu. Bạn giải thích lại được không?"],
  ["satisfied", "adj", "ˈsætɪsfaɪd", "hài lòng", "Are you satisfied with the service?", "Bạn có hài lòng với dịch vụ không?"],
  ["homesick", "adj", "ˈhoʊmsɪk", "nhớ nhà", "She felt homesick during her first year abroad.", "Cô ấy nhớ nhà trong năm đầu ở nước ngoài."],
  ["kind", "adj", "kaɪnd", "tốt bụng", "Our neighbor is very kind to us.", "Hàng xóm rất tốt với chúng tôi."],
  ["honest", "adj", "ˈɑːnɪst", "thật thà, trung thực", "Please be honest with me.", "Làm ơn hãy thành thật với tôi."],
  ["generous", "adj", "ˈdʒenərəs", "hào phóng", "My uncle is generous with his time and money.", "Chú tôi rất hào phóng cả thời gian lẫn tiền bạc."],
  ["funny", "adj", "ˈfʌni", "hài hước, buồn cười", "He tells really funny stories.", "Anh ấy kể chuyện rất hài hước."],
  ["polite", "adj", "pəˈlaɪt", "lịch sự", "Children should be polite to older people.", "Trẻ con nên lễ phép với người lớn."],
  ["rude", "adj", "ruːd", "thô lỗ, bất lịch sự", "It's rude to use your phone during dinner.", "Dùng điện thoại trong bữa tối là bất lịch sự."],
  ["selfish", "adj", "ˈselfɪʃ", "ích kỷ", "Don't be selfish. Share with your brother.", "Đừng ích kỷ thế. Chia cho em đi."],
  ["hard-working", "adj", "ˌhɑːrdˈwɝːkɪŋ", "chăm chỉ", "Vietnamese farmers are very hard-working.", "Nông dân Việt Nam rất chăm chỉ."],
  ["outgoing", "adj", "ˈaʊtˌɡoʊɪŋ", "hòa đồng, cởi mở", "She's outgoing and makes friends easily.", "Cô ấy hòa đồng và dễ kết bạn."],
  ["stubborn", "adj", "ˈstʌbɚn", "bướng bỉnh", "My grandfather is too stubborn to see a doctor.", "Ông tôi bướng đến mức không chịu đi khám."],
  ["careful", "adj", "ˈkerfəl", "cẩn thận", "Be careful when you cross the street.", "Cẩn thận khi qua đường nhé."],
  ["cheerful", "adj", "ˈtʃɪrfəl", "vui tươi, tươi tắn", "She's always cheerful in the morning.", "Buổi sáng cô ấy lúc nào cũng tươi tắn."],
]);

extendTopic("tech", "Công nghệ", [
  ["laptop", "n", "ˈlæptɑːp", "máy tính xách tay", "I bought a new laptop for work.", "Tôi mua một chiếc laptop mới để làm việc."],
  ["smartphone", "n", "ˈsmɑːrtfoʊn", "điện thoại thông minh", "Almost everyone has a smartphone now.", "Bây giờ hầu như ai cũng có điện thoại thông minh."],
  ["charger", "n", "ˈtʃɑːrdʒɚ", "cục sạc", "Can I borrow your phone charger?", "Cho mình mượn sạc điện thoại được không?"],
  ["keyboard", "n", "ˈkiːbɔːrd", "bàn phím", "Some keys on my keyboard don't work.", "Vài phím trên bàn phím của tôi bị liệt."],
  ["headphones", "n", "ˈhedfoʊnz", "tai nghe", "He always wears headphones on the bus.", "Anh ấy lúc nào cũng đeo tai nghe trên xe buýt."],
  ["app", "n", "æp", "ứng dụng", "I use an app to order a Grab bike.", "Tôi dùng ứng dụng để đặt xe ôm Grab."],
  ["website", "n", "ˈwebsaɪt", "trang web", "You can find more information on our website.", "Bạn có thể xem thêm thông tin trên trang web của chúng tôi."],
  ["Wi-Fi", "n", "ˈwaɪfaɪ", "mạng Wi-Fi", "What's the Wi-Fi password here?", "Mật khẩu Wi-Fi ở đây là gì vậy?"],
  ["internet", "n", "ˈɪntɚnet", "mạng internet", "The internet is very slow today.", "Hôm nay mạng rất chậm."],
  ["email", "n", "ˈiːmeɪl", "thư điện tử", "I'll send you an email tomorrow.", "Mai tôi sẽ gửi email cho bạn."],
  ["message", "n", "ˈmesɪdʒ", "tin nhắn", "I got your message on Zalo.", "Tôi nhận được tin nhắn Zalo của bạn rồi."],
  ["file", "n", "faɪl", "tệp tin", "Please save the file before you close it.", "Hãy lưu tệp trước khi đóng."],
  ["folder", "n", "ˈfoʊldɚ", "thư mục", "Put all the photos in one folder.", "Để tất cả ảnh vào một thư mục."],
  ["upload", "v", "ˌʌpˈloʊd", "tải lên", "She uploaded the video to YouTube.", "Cô ấy đã tải video lên YouTube."],
  ["install", "v", "ɪnˈstɑːl", "cài đặt", "You need to install this app first.", "Bạn cần cài ứng dụng này trước."],
  ["click", "v", "klɪk", "nhấp chuột, bấm", "Click here to see more.", "Bấm vào đây để xem thêm."],
  ["type", "v", "taɪp", "gõ (phím)", "She can type very fast.", "Cô ấy gõ phím rất nhanh."],
  ["copy", "v", "ˈkɑːpi", "sao chép", "Copy this link and send it to me.", "Sao chép đường link này rồi gửi cho mình."],
  ["paste", "v", "peɪst", "dán", "Paste the text into the message box.", "Dán đoạn chữ vào ô tin nhắn."],
  ["print", "v", "prɪnt", "in", "Can you print this document for me?", "Bạn in giúp mình tài liệu này được không?"],
  ["social media", "n", "ˌsoʊʃəl ˈmiːdiə", "mạng xã hội", "Teenagers spend hours on social media.", "Thanh thiếu niên dành hàng giờ trên mạng xã hội."],
  ["selfie", "n", "ˈselfi", "ảnh tự chụp", "Let's take a selfie together!", "Mình chụp ảnh selfie chung đi!"],
  ["restart", "v", "ˌriːˈstɑːrt", "khởi động lại", "Try restarting your computer.", "Thử khởi động lại máy tính xem."],
  ["crash", "v", "kræʃ", "bị treo, bị sập (máy)", "My computer crashed and I lost my work.", "Máy tính bị treo và tôi mất hết bài."],
  ["share", "v", "ʃer", "chia sẻ", "She shared the photos on Facebook.", "Cô ấy đã chia sẻ ảnh lên Facebook."],
  ["post", "v", "poʊst", "đăng (bài)", "He posts a new video every week.", "Tuần nào anh ấy cũng đăng một video mới."],
  ["notification", "n", "ˌnoʊtəfəˈkeɪʃən", "thông báo", "I turned off all notifications at night.", "Tôi tắt hết thông báo vào ban đêm."],
  ["device", "n", "dɪˈvaɪs", "thiết bị", "You can log in on two devices.", "Bạn có thể đăng nhập trên hai thiết bị."],
]);

extendTopic("time", "Thời gian & thời tiết", [
  ["rainy", "adj", "ˈreɪni", "có mưa", "It's rainy in Saigon from May to October.", "Sài Gòn mưa nhiều từ tháng Năm đến tháng Mười."],
  ["cloudy", "adj", "ˈklaʊdi", "nhiều mây", "It's cloudy, but it won't rain.", "Trời nhiều mây nhưng sẽ không mưa đâu."],
  ["windy", "adj", "ˈwɪndi", "có gió", "It's too windy to go to the beach.", "Gió to quá, không đi biển được."],
  ["foggy", "adj", "ˈfɑːɡi", "có sương mù", "Da Lat is often foggy in the morning.", "Buổi sáng Đà Lạt thường có sương mù."],
  ["hot", "adj", "hɑːt", "nóng", "It's really hot in Hanoi in summer.", "Mùa hè ở Hà Nội rất nóng."],
  ["cool", "adj", "kuːl", "mát mẻ", "The evening air is cool and fresh.", "Không khí buổi tối mát mẻ và trong lành."],
  ["decade", "n", "ˈdekeɪd", "thập kỷ, mười năm", "We have lived here for a decade.", "Chúng tôi đã sống ở đây mười năm rồi."],
  ["thunder", "n", "ˈθʌndɚ", "sấm", "The baby woke up because of the thunder.", "Em bé thức giấc vì tiếng sấm."],
  ["lightning", "n", "ˈlaɪtnɪŋ", "tia chớp", "Stay inside when there's lightning.", "Hãy ở trong nhà khi có sấm chớp."],
  ["typhoon", "n", "taɪˈfuːn", "bão (nhiệt đới)", "A typhoon is coming to central Vietnam.", "Một cơn bão sắp đổ bộ vào miền Trung."],
  ["flood", "n", "flʌd", "lũ lụt, ngập", "There was a flood after the heavy rain.", "Đã có lũ sau trận mưa lớn."],
  ["midnight", "n", "ˈmɪdnaɪt", "nửa đêm", "The party ended at midnight.", "Bữa tiệc kết thúc lúc nửa đêm."],
  ["noon", "n", "nuːn", "buổi trưa (12 giờ)", "Let's meet at noon for lunch.", "Mình gặp nhau lúc mười hai giờ trưa ăn cơm nhé."],
  ["tonight", "adv", "təˈnaɪt", "tối nay", "What are you doing tonight?", "Tối nay bạn làm gì?"],
  ["tomorrow", "adv", "təˈmɑːroʊ", "ngày mai", "I'll call you tomorrow morning.", "Sáng mai tôi sẽ gọi cho bạn."],
  ["yesterday", "adv", "ˈjestɚdeɪ", "hôm qua", "It rained all day yesterday.", "Hôm qua mưa cả ngày."],
  ["hour", "n", "aʊr", "giờ, tiếng đồng hồ", "The bus ride takes two hours.", "Đi xe buýt mất hai tiếng."],
  ["minute", "n", "ˈmɪnɪt", "phút", "Wait a minute, I'm almost ready.", "Chờ một phút, mình sắp xong rồi."],
  ["calendar", "n", "ˈkæləndɚ", "lịch", "I wrote the date on my calendar.", "Tôi đã ghi ngày đó vào lịch."],
  ["date", "n", "deɪt", "ngày tháng", "What's the date today?", "Hôm nay là ngày bao nhiêu?"],
  ["month", "n", "mʌnθ", "tháng", "I'll finish the course next month.", "Tháng sau tôi sẽ học xong khóa học."],
  ["late", "adj", "leɪt", "muộn, trễ", "Sorry I'm late. The traffic was terrible.", "Xin lỗi mình đến muộn. Kẹt xe kinh khủng."],
  ["soon", "adv", "suːn", "sớm, chẳng bao lâu nữa", "Tet is coming soon.", "Sắp đến Tết rồi."],
  ["recently", "adv", "ˈriːsəntli", "gần đây", "I've been very busy recently.", "Gần đây tôi rất bận."],
  ["usually", "adv", "ˈjuːʒuəli", "thường thường", "I usually have pho for breakfast.", "Tôi thường ăn phở vào bữa sáng."],
  ["sometimes", "adv", "ˈsʌmtaɪmz", "thỉnh thoảng", "We sometimes eat out on Sundays.", "Thỉnh thoảng chúng tôi ăn ngoài vào Chủ nhật."],
  ["in a hurry", "phr", "ɪn ə ˈhɝːi", "vội vàng", "Sorry, I'm in a hurry right now.", "Xin lỗi, bây giờ tôi đang vội."],
  ["in time", "phr", "ɪn taɪm", "kịp lúc", "We got to the station just in time.", "Chúng tôi đến ga vừa kịp lúc."],
]);

extendTopic("hobbies", "Sở thích & thể thao", [
  ["hobby", "n", "ˈhɑːbi", "sở thích", "What's your favorite hobby?", "Sở thích yêu thích của bạn là gì?"],
  ["free time", "n", "ˌfriː ˈtaɪm", "thời gian rảnh", "What do you do in your free time?", "Bạn làm gì vào thời gian rảnh?"],
  ["reading", "n", "ˈriːdɪŋ", "việc đọc sách", "Reading helps me relax before bed.", "Đọc sách giúp tôi thư giãn trước khi ngủ."],
  ["painting", "n", "ˈpeɪntɪŋ", "vẽ tranh (màu)", "She took up painting last year.", "Cô ấy bắt đầu vẽ tranh từ năm ngoái."],
  ["drawing", "n", "ˈdrɑːɪŋ", "vẽ (bằng bút chì, bút)", "My son loves drawing cartoon characters.", "Con trai tôi rất thích vẽ nhân vật hoạt hình."],
  ["photography", "n", "fəˈtɑːɡrəfi", "nhiếp ảnh", "He's really into photography.", "Anh ấy rất mê nhiếp ảnh."],
  ["gardening", "n", "ˈɡɑːrdənɪŋ", "làm vườn", "My grandma enjoys gardening every morning.", "Bà tôi thích làm vườn mỗi sáng."],
  ["fishing", "n", "ˈfɪʃɪŋ", "câu cá", "Dad goes fishing at the lake on Sundays.", "Chủ nhật bố đi câu cá ở hồ."],
  ["camping", "n", "ˈkæmpɪŋ", "cắm trại", "We went camping in the mountains.", "Chúng tôi đi cắm trại trên núi."],
  ["hiking", "n", "ˈhaɪkɪŋ", "đi bộ đường dài, leo núi", "Hiking in Sapa is amazing.", "Đi bộ leo núi ở Sa Pa rất tuyệt."],
  ["jogging", "n", "ˈdʒɑːɡɪŋ", "chạy bộ", "I go jogging around the lake every morning.", "Sáng nào tôi cũng chạy bộ quanh hồ."],
  ["swimming", "n", "ˈswɪmɪŋ", "bơi lội", "Swimming is good for your health.", "Bơi lội tốt cho sức khỏe."],
  ["cycling", "n", "ˈsaɪklɪŋ", "đạp xe", "Cycling is popular in Hoi An.", "Đạp xe rất phổ biến ở Hội An."],
  ["yoga", "n", "ˈjoʊɡə", "yoga", "My mom does yoga three times a week.", "Mẹ tôi tập yoga ba lần một tuần."],
  ["gym", "n", "dʒɪm", "phòng tập thể hình", "I go to the gym after work.", "Tôi đi tập gym sau giờ làm."],
  ["soccer", "n", "ˈsɑːkɚ", "bóng đá", "Vietnamese people love watching soccer.", "Người Việt rất thích xem bóng đá."],
  ["basketball", "n", "ˈbæskətbɑːl", "bóng rổ", "They play basketball after school.", "Họ chơi bóng rổ sau giờ học."],
  ["badminton", "n", "ˈbædmɪntən", "cầu lông", "We play badminton in the park.", "Chúng tôi chơi cầu lông trong công viên."],
  ["volleyball", "n", "ˈvɑːlibɑːl", "bóng chuyền", "Let's play volleyball on the beach.", "Mình chơi bóng chuyền trên bãi biển đi."],
  ["table tennis", "n", "ˈteɪbəl ˌtenɪs", "bóng bàn", "My dad is good at table tennis.", "Bố tôi chơi bóng bàn giỏi."],
  ["chess", "n", "tʃes", "cờ vua", "Can you teach me how to play chess?", "Bạn dạy mình chơi cờ vua được không?"],
  ["knitting", "n", "ˈnɪtɪŋ", "đan len", "My grandmother loves knitting in the evening.", "Bà tôi rất thích đan len vào buổi tối."],
  ["player", "n", "ˈpleɪɚ", "cầu thủ, người chơi", "He's the best player on the team.", "Anh ấy là cầu thủ giỏi nhất đội."],
  ["match", "n", "mætʃ", "trận đấu", "Did you watch the match last night?", "Tối qua bạn có xem trận đấu không?"],
  ["score", "v", "skɔːr", "ghi bàn, ghi điểm", "He scored two goals in the first half.", "Anh ấy ghi hai bàn trong hiệp một."],
  ["win", "v", "wɪn", "thắng", "Vietnam won the match 2–0.", "Việt Nam thắng trận đấu 2–0."],
  ["lose", "v", "luːz", "thua", "We lost the game, but we had fun.", "Chúng tôi thua nhưng vẫn rất vui."],
  ["competition", "n", "ˌkɑːmpəˈtɪʃən", "cuộc thi", "She won first prize in the competition.", "Cô ấy đạt giải nhất trong cuộc thi."],
  ["practice", "v", "ˈpræktɪs", "luyện tập", "The team practices every evening.", "Cả đội luyện tập mỗi tối."],
  ["fan", "n", "fæn", "người hâm mộ", "Thousands of fans came to the stadium.", "Hàng nghìn người hâm mộ đã đến sân vận động."],
  ["stadium", "n", "ˈsteɪdiəm", "sân vận động", "My Dinh Stadium is in Hanoi.", "Sân vận động Mỹ Đình ở Hà Nội."],
  ["collect", "v", "kəˈlekt", "sưu tầm", "My brother collects old coins.", "Anh trai tôi sưu tầm tiền xu cũ."],
  ["board game", "n", "ˈbɔːrd ɡeɪm", "trò chơi bàn cờ", "We play board games on Friday nights.", "Tối thứ Sáu chúng tôi chơi board game."],
  ["video game", "n", "ˈvɪdioʊ ˌɡeɪm", "trò chơi điện tử", "He plays video games too much.", "Cậu ấy chơi điện tử nhiều quá."],
  ["puzzle", "n", "ˈpʌzəl", "trò xếp hình, câu đố", "It took us two days to finish the puzzle.", "Chúng tôi mất hai ngày để ghép xong bức tranh."],
  ["work out", "phr", "wɝːk ˈaʊt", "tập thể dục, tập luyện", "I work out at home every morning.", "Sáng nào tôi cũng tập thể dục ở nhà."],
  ["take up", "phr", "teɪk ˈʌp", "bắt đầu (một sở thích)", "I want to take up the guitar.", "Tôi muốn bắt đầu học chơi guitar."],
  ["be into", "phr", "bi ˈɪntuː", "mê, thích", "My sister is into K-pop dance.", "Em gái tôi mê nhảy K-pop."],
  ["goal", "n", "ɡoʊl", "bàn thắng", "What a beautiful goal!", "Bàn thắng đẹp quá!"],
  ["martial arts", "n", "ˌmɑːrʃəl ˈɑːrts", "võ thuật", "Vovinam is a Vietnamese martial art.", "Vovinam là một môn võ thuật Việt Nam."],
]);
