// Bộ từ vựng khởi đầu: 10 chủ đề x 12 từ, phiên âm Anh-Mỹ.
// Mỗi từ: [từ, loại từ, phiên âm, nghĩa, câu ví dụ, dịch câu ví dụ]
const POS_VI = { n: "danh từ", v: "động từ", adj: "tính từ", adv: "trạng từ", phr: "cụm từ" };

const TOPICS = [
  { id: "people", name: "Gia đình & mọi người", words: [
    ["family", "n", "ˈfæməli", "gia đình", "My family lives in Da Nang.", "Gia đình tôi sống ở Đà Nẵng."],
    ["parents", "n", "ˈperənts", "bố mẹ", "My parents are both teachers.", "Bố mẹ tôi đều là giáo viên."],
    ["husband", "n", "ˈhʌzbənd", "chồng", "Her husband works at a bank.", "Chồng cô ấy làm ở ngân hàng."],
    ["wife", "n", "waɪf", "vợ", "His wife is a nurse.", "Vợ anh ấy là y tá."],
    ["daughter", "n", "ˈdɑːtɚ", "con gái", "They have a daughter and a son.", "Họ có một con gái và một con trai."],
    ["grandmother", "n", "ˈɡrænmʌðɚ", "bà", "My grandmother makes the best spring rolls.", "Bà tôi làm nem ngon nhất."],
    ["cousin", "n", "ˈkʌzən", "anh chị em họ", "My cousin is studying in Australia.", "Em họ tôi đang du học ở Úc."],
    ["relative", "n", "ˈrelətɪv", "họ hàng", "We visit our relatives during Tet.", "Chúng tôi đi thăm họ hàng dịp Tết."],
    ["neighbor", "n", "ˈneɪbɚ", "hàng xóm", "Our neighbors are very friendly.", "Hàng xóm nhà tôi rất thân thiện."],
    ["raise", "v", "reɪz", "nuôi nấng", "She raised three children on her own.", "Bà ấy một mình nuôi ba người con."],
    ["get along", "phr", "ɡet əˈlɑːŋ", "hòa thuận", "I get along well with my sister.", "Tôi rất hòa thuận với chị gái."],
    ["look after", "phr", "lʊk ˈæftɚ", "chăm sóc, trông nom", "Can you look after my cat this weekend?", "Cuối tuần này bạn trông con mèo giúp mình được không?"],
  ]},
  { id: "food", name: "Ăn uống", words: [
    ["breakfast", "n", "ˈbrekfəst", "bữa sáng", "I usually have bread for breakfast.", "Tôi thường ăn bánh mì vào bữa sáng."],
    ["hungry", "adj", "ˈhʌŋɡri", "đói", "I'm hungry. Let's eat.", "Mình đói rồi. Đi ăn thôi."],
    ["delicious", "adj", "dɪˈlɪʃəs", "ngon", "This soup is delicious!", "Món súp này ngon quá!"],
    ["spicy", "adj", "ˈspaɪsi", "cay", "Is this dish spicy?", "Món này có cay không?"],
    ["order", "v", "ˈɔːrdɚ", "gọi món, đặt hàng", "Are you ready to order?", "Anh chị gọi món chưa ạ?"],
    ["menu", "n", "ˈmenjuː", "thực đơn", "Could I see the menu, please?", "Cho tôi xem thực đơn được không?"],
    ["bill", "n", "bɪl", "hóa đơn", "Can we have the bill, please?", "Cho chúng tôi xin hóa đơn."],
    ["vegetable", "n", "ˈvedʒtəbəl", "rau củ", "Eat more vegetables every day.", "Hãy ăn nhiều rau hơn mỗi ngày."],
    ["recipe", "n", "ˈresəpi", "công thức nấu ăn", "Can you share the recipe?", "Bạn chia sẻ công thức được không?"],
    ["boil", "v", "bɔɪl", "luộc, đun sôi", "Boil the eggs for eight minutes.", "Luộc trứng trong tám phút."],
    ["fried", "adj", "fraɪd", "chiên, rán", "I'd like fried rice with egg.", "Tôi muốn cơm chiên trứng."],
    ["takeout", "n", "ˈteɪkaʊt", "đồ ăn mua mang về", "Let's get takeout tonight.", "Tối nay mình mua đồ ăn về nhé."],
  ]},
  { id: "shopping", name: "Mua sắm & tiền bạc", words: [
    ["price", "n", "praɪs", "giá", "The price is too high.", "Giá cao quá."],
    ["cheap", "adj", "tʃiːp", "rẻ", "This shirt is really cheap.", "Cái áo này rẻ thật."],
    ["expensive", "adj", "ɪkˈspensɪv", "đắt", "Rent in the city is expensive.", "Tiền thuê nhà ở thành phố đắt."],
    ["discount", "n", "ˈdɪskaʊnt", "sự giảm giá", "Is there a discount for students?", "Có giảm giá cho sinh viên không?"],
    ["afford", "v", "əˈfɔːrd", "có đủ tiền (mua, trả)", "I can't afford a new phone right now.", "Giờ tôi chưa đủ tiền mua điện thoại mới."],
    ["cash", "n", "kæʃ", "tiền mặt", "Do you pay in cash or by card?", "Anh trả tiền mặt hay quẹt thẻ?"],
    ["change", "n", "tʃeɪndʒ", "tiền thối lại, tiền lẻ", "Here is your change.", "Tiền thối của anh đây."],
    ["receipt", "n", "rɪˈsiːt", "biên lai", "Keep the receipt in case you need to return it.", "Giữ biên lai phòng khi cần đổi trả."],
    ["size", "n", "saɪz", "cỡ, kích thước", "Do you have this in a smaller size?", "Cái này có cỡ nhỏ hơn không?"],
    ["try on", "phr", "traɪ ˈɑːn", "mặc thử, đi thử", "Can I try on these shoes?", "Tôi đi thử đôi giày này được không?"],
    ["save", "v", "seɪv", "tiết kiệm", "I save money every month.", "Tháng nào tôi cũng tiết kiệm tiền."],
    ["spend", "v", "spend", "tiêu (tiền), dành (thời gian)", "How much do you spend on food?", "Bạn tiêu bao nhiêu tiền cho ăn uống?"],
  ]},
  { id: "work", name: "Công việc", words: [
    ["job", "n", "dʒɑːb", "công việc", "She got a new job last month.", "Cô ấy có việc mới hồi tháng trước."],
    ["colleague", "n", "ˈkɑːliːɡ", "đồng nghiệp", "My colleagues are very helpful.", "Đồng nghiệp của tôi rất hay giúp đỡ."],
    ["boss", "n", "bɑːs", "sếp", "My boss is on a business trip.", "Sếp tôi đang đi công tác."],
    ["meeting", "n", "ˈmiːtɪŋ", "cuộc họp", "The meeting starts at nine.", "Cuộc họp bắt đầu lúc chín giờ."],
    ["deadline", "n", "ˈdedlaɪn", "hạn chót", "The deadline is next Friday.", "Hạn chót là thứ Sáu tuần sau."],
    ["salary", "n", "ˈsælɚi", "lương", "He asked for a higher salary.", "Anh ấy đề nghị tăng lương."],
    ["interview", "n", "ˈɪntɚvjuː", "buổi phỏng vấn", "I have a job interview tomorrow.", "Ngày mai tôi có buổi phỏng vấn xin việc."],
    ["experience", "n", "ɪkˈspɪriəns", "kinh nghiệm", "Do you have any experience in sales?", "Bạn có kinh nghiệm bán hàng không?"],
    ["skill", "n", "skɪl", "kỹ năng", "Communication is an important skill.", "Giao tiếp là một kỹ năng quan trọng."],
    ["apply", "v", "əˈplaɪ", "nộp đơn, ứng tuyển", "I applied for three jobs this week.", "Tuần này tôi đã ứng tuyển ba công việc."],
    ["busy", "adj", "ˈbɪzi", "bận", "I'm busy right now. Can I call you later?", "Giờ mình đang bận. Lát mình gọi lại nhé?"],
    ["overtime", "n", "ˈoʊvɚtaɪm", "làm thêm giờ", "We worked overtime to finish the project.", "Chúng tôi làm thêm giờ để xong dự án."],
  ]},
  { id: "travel", name: "Du lịch & đi lại", words: [
    ["ticket", "n", "ˈtɪkɪt", "vé", "I booked a train ticket to Hue.", "Tôi đã đặt vé tàu đi Huế."],
    ["book", "v", "bʊk", "đặt (chỗ, phòng, vé)", "I'd like to book a room for two nights.", "Tôi muốn đặt một phòng hai đêm."],
    ["luggage", "n", "ˈlʌɡɪdʒ", "hành lý", "How much luggage can I bring?", "Tôi được mang bao nhiêu hành lý?"],
    ["passport", "n", "ˈpæspɔːrt", "hộ chiếu", "Don't forget your passport.", "Đừng quên hộ chiếu nhé."],
    ["flight", "n", "flaɪt", "chuyến bay", "Our flight was delayed for two hours.", "Chuyến bay của chúng tôi bị hoãn hai tiếng."],
    ["destination", "n", "ˌdestəˈneɪʃən", "điểm đến", "Da Lat is a popular destination.", "Đà Lạt là một điểm đến được yêu thích."],
    ["map", "n", "mæp", "bản đồ", "Can you show me on the map?", "Bạn chỉ cho mình trên bản đồ được không?"],
    ["traffic jam", "n", "ˈtræfɪk dʒæm", "tắc đường", "I was late because of a traffic jam.", "Tôi đến muộn vì tắc đường."],
    ["turn left", "phr", "tɝːn ˈleft", "rẽ trái", "Turn left at the next corner.", "Rẽ trái ở góc đường tiếp theo."],
    ["far", "adj", "fɑːr", "xa", "Is the airport far from here?", "Sân bay có xa đây không?"],
    ["sightseeing", "n", "ˈsaɪtsiːɪŋ", "việc tham quan", "We went sightseeing in Hoi An.", "Chúng tôi đi tham quan ở Hội An."],
    ["souvenir", "n", "ˌsuːvəˈnɪr", "quà lưu niệm", "I bought some souvenirs for my friends.", "Tôi mua vài món quà lưu niệm cho bạn bè."],
  ]},
  { id: "home", name: "Nhà cửa & sinh hoạt", words: [
    ["wake up", "phr", "weɪk ˈʌp", "thức dậy", "I wake up at six every morning.", "Sáng nào tôi cũng dậy lúc sáu giờ."],
    ["brush", "v", "brʌʃ", "chải, đánh (răng)", "Brush your teeth before bed.", "Đánh răng trước khi đi ngủ nhé."],
    ["laundry", "n", "ˈlɑːndri", "việc giặt giũ, đồ cần giặt", "I do the laundry on Sundays.", "Tôi giặt đồ vào Chủ nhật."],
    ["clean", "v", "kliːn", "dọn dẹp, lau chùi", "Let's clean the kitchen together.", "Mình cùng dọn bếp nhé."],
    ["rent", "n", "rent", "tiền thuê nhà", "The rent is due at the start of the month.", "Tiền thuê nhà phải trả vào đầu tháng."],
    ["apartment", "n", "əˈpɑːrtmənt", "căn hộ", "We live in a small apartment.", "Chúng tôi sống trong một căn hộ nhỏ."],
    ["furniture", "n", "ˈfɝːnɪtʃɚ", "đồ nội thất", "We need some new furniture.", "Chúng tôi cần mua thêm đồ nội thất."],
    ["messy", "adj", "ˈmesi", "bừa bộn", "My room is so messy.", "Phòng tôi bừa bộn quá."],
    ["neighborhood", "n", "ˈneɪbɚhʊd", "khu phố, khu vực", "It's a quiet neighborhood.", "Đây là một khu phố yên tĩnh."],
    ["turn off", "phr", "tɝːn ˈɑːf", "tắt (đèn, máy)", "Turn off the lights when you leave.", "Nhớ tắt đèn khi ra ngoài."],
    ["take a nap", "phr", "teɪk ə ˈnæp", "ngủ trưa, chợp mắt", "I usually take a nap after lunch.", "Tôi thường ngủ trưa sau bữa trưa."],
    ["chores", "n", "tʃɔːrz", "việc nhà", "Everyone in my family shares the chores.", "Cả nhà tôi cùng chia nhau làm việc nhà."],
  ]},
  { id: "health", name: "Sức khỏe", words: [
    ["headache", "n", "ˈhedeɪk", "chứng đau đầu", "I have a terrible headache.", "Tôi đau đầu kinh khủng."],
    ["fever", "n", "ˈfiːvɚ", "cơn sốt", "The baby has a high fever.", "Em bé bị sốt cao."],
    ["cough", "n", "kɑːf", "cơn ho", "You should see a doctor about that cough.", "Bạn nên đi khám vì cơn ho đó."],
    ["medicine", "n", "ˈmedɪsən", "thuốc", "Take this medicine twice a day.", "Uống thuốc này ngày hai lần."],
    ["appointment", "n", "əˈpɔɪntmənt", "lịch hẹn", "I have a dentist appointment at 3 p.m.", "Tôi có lịch hẹn nha sĩ lúc 3 giờ chiều."],
    ["exercise", "v", "ˈeksɚsaɪz", "tập thể dục", "I exercise for 30 minutes a day.", "Mỗi ngày tôi tập thể dục 30 phút."],
    ["healthy", "adj", "ˈhelθi", "khỏe mạnh, lành mạnh", "She eats healthy food.", "Cô ấy ăn đồ ăn lành mạnh."],
    ["tired", "adj", "ˈtaɪɚd", "mệt", "I'm too tired to go out tonight.", "Tối nay tôi mệt quá, không muốn ra ngoài."],
    ["sore throat", "n", "ˌsɔːr ˈθroʊt", "đau họng", "I've had a sore throat since yesterday.", "Tôi bị đau họng từ hôm qua."],
    ["rest", "v", "rest", "nghỉ ngơi", "You need to rest for a few days.", "Bạn cần nghỉ ngơi vài ngày."],
    ["hurt", "v", "hɝːt", "đau, làm đau", "My back hurts.", "Lưng tôi đau."],
    ["recover", "v", "rɪˈkʌvɚ", "hồi phục", "He recovered quickly after the surgery.", "Anh ấy hồi phục nhanh sau ca phẫu thuật."],
  ]},
  { id: "feelings", name: "Cảm xúc & tính cách", words: [
    ["excited", "adj", "ɪkˈsaɪtɪd", "háo hức, hào hứng", "I'm so excited about the trip!", "Mình háo hức về chuyến đi quá!"],
    ["nervous", "adj", "ˈnɝːvəs", "hồi hộp", "I always feel nervous before exams.", "Tôi luôn thấy hồi hộp trước kỳ thi."],
    ["worried", "adj", "ˈwɝːid", "lo lắng", "She is worried about her exam results.", "Cô ấy lo về kết quả thi."],
    ["bored", "adj", "bɔːrd", "chán", "I'm bored. Let's do something fun.", "Chán quá. Làm gì đó vui đi."],
    ["proud", "adj", "praʊd", "tự hào", "My parents are proud of me.", "Bố mẹ tự hào về tôi."],
    ["upset", "adj", "ʌpˈset", "buồn bực, khó chịu", "She was upset because she missed the bus.", "Cô ấy buồn bực vì lỡ chuyến xe buýt."],
    ["embarrassed", "adj", "ɪmˈberəst", "xấu hổ, ngượng", "I was embarrassed when I forgot his name.", "Tôi thấy ngượng khi quên tên anh ấy."],
    ["friendly", "adj", "ˈfrendli", "thân thiện", "The staff here are very friendly.", "Nhân viên ở đây rất thân thiện."],
    ["patient", "adj", "ˈpeɪʃənt", "kiên nhẫn", "Be patient. Learning a language takes time.", "Hãy kiên nhẫn. Học ngoại ngữ cần thời gian."],
    ["shy", "adj", "ʃaɪ", "nhút nhát", "He is shy, but he is very kind.", "Anh ấy nhút nhát nhưng rất tốt bụng."],
    ["lazy", "adj", "ˈleɪzi", "lười", "I feel lazy on rainy days.", "Những ngày mưa tôi thấy lười."],
    ["confident", "adj", "ˈkɑːnfədənt", "tự tin", "Practice makes you more confident.", "Luyện tập giúp bạn tự tin hơn."],
  ]},
  { id: "tech", name: "Công nghệ", words: [
    ["download", "v", "ˈdaʊnloʊd", "tải xuống", "Download the app to order food.", "Tải ứng dụng về để đặt đồ ăn."],
    ["password", "n", "ˈpæswɝːd", "mật khẩu", "Never share your password with anyone.", "Đừng bao giờ chia sẻ mật khẩu với ai."],
    ["charge", "v", "tʃɑːrdʒ", "sạc (pin)", "I need to charge my phone.", "Tôi cần sạc điện thoại."],
    ["battery", "n", "ˈbætɚi", "pin", "My battery is almost dead.", "Điện thoại tôi sắp hết pin."],
    ["screen", "n", "skriːn", "màn hình", "The screen is cracked.", "Màn hình bị nứt rồi."],
    ["update", "v", "ʌpˈdeɪt", "cập nhật", "Please update the app to the latest version.", "Hãy cập nhật ứng dụng lên bản mới nhất."],
    ["account", "n", "əˈkaʊnt", "tài khoản", "Create an account to save your progress.", "Tạo tài khoản để lưu tiến độ học."],
    ["search", "v", "sɝːtʃ", "tìm kiếm", "I searched for it online.", "Tôi đã tìm nó trên mạng."],
    ["log in", "phr", "lɑːɡ ˈɪn", "đăng nhập", "Log in with your email address.", "Đăng nhập bằng địa chỉ email của bạn."],
    ["delete", "v", "dɪˈliːt", "xóa", "I accidentally deleted the photo.", "Tôi lỡ tay xóa mất bức ảnh."],
    ["signal", "n", "ˈsɪɡnəl", "sóng, tín hiệu", "There's no signal in the mountains.", "Trên núi không có sóng."],
    ["online", "adv", "ˌɑːnˈlaɪn", "trực tuyến, trên mạng", "I take English classes online.", "Tôi học tiếng Anh trực tuyến."],
  ]},
  { id: "time", name: "Thời gian & thời tiết", words: [
    ["weather", "n", "ˈweðɚ", "thời tiết", "The weather is lovely today.", "Hôm nay thời tiết đẹp quá."],
    ["sunny", "adj", "ˈsʌni", "có nắng", "It's sunny and hot in Saigon.", "Sài Gòn trời nắng và nóng."],
    ["humid", "adj", "ˈhjuːmɪd", "ẩm, oi", "Hanoi is very humid in the summer.", "Hà Nội mùa hè rất oi ẩm."],
    ["umbrella", "n", "ʌmˈbrelə", "cái ô, cái dù", "Take an umbrella. It might rain.", "Mang ô theo nhé. Trời có thể mưa."],
    ["storm", "n", "stɔːrm", "cơn bão", "The storm caused flooding in many areas.", "Cơn bão gây ngập lụt ở nhiều nơi."],
    ["forecast", "n", "ˈfɔːrkæst", "dự báo", "The forecast says it will rain tomorrow.", "Dự báo nói ngày mai trời mưa."],
    ["freezing", "adj", "ˈfriːzɪŋ", "lạnh cóng", "It's freezing outside!", "Ngoài trời lạnh cóng!"],
    ["early", "adv", "ˈɝːli", "sớm", "I got up early to catch the bus.", "Tôi dậy sớm để kịp xe buýt."],
    ["weekend", "n", "ˈwiːkend", "cuối tuần", "What are you doing this weekend?", "Cuối tuần này bạn làm gì?"],
    ["schedule", "n", "ˈskedʒuːl", "lịch trình", "Let me check my schedule.", "Để mình xem lịch đã."],
    ["on time", "phr", "ɑːn ˈtaɪm", "đúng giờ", "The train left on time.", "Tàu chạy đúng giờ."],
    ["season", "n", "ˈsiːzən", "mùa", "My favorite season is autumn.", "Mùa tôi thích nhất là mùa thu."],
  ]},
];
