// Bộ từ vựng bổ sung D: nghề nghiệp, thành phố, động từ và tính từ thông dụng.
extendTopic("jobs", "Nghề nghiệp", [
  ["engineer", "n", "ˌendʒɪˈnɪr", "kỹ sư", "My brother is a software engineer.", "Anh trai tôi là kỹ sư phần mềm."],
  ["accountant", "n", "əˈkaʊntənt", "kế toán", "The accountant checks the company's accounts every month.", "Kế toán kiểm tra sổ sách công ty mỗi tháng."],
  ["lawyer", "n", "ˈlɔɪɚ", "luật sư", "You should talk to a lawyer first.", "Bạn nên nói chuyện với luật sư trước."],
  ["architect", "n", "ˈɑːrkətekt", "kiến trúc sư", "An architect designed our new house.", "Một kiến trúc sư đã thiết kế ngôi nhà mới của chúng tôi."],
  ["pharmacist", "n", "ˈfɑːrməsɪst", "dược sĩ", "Ask the pharmacist how to take this medicine.", "Hãy hỏi dược sĩ cách uống thuốc này."],
  ["dentist", "n", "ˈdentɪst", "nha sĩ", "I go to the dentist twice a year.", "Tôi đi khám nha sĩ hai lần một năm."],
  ["mechanic", "n", "məˈkænɪk", "thợ sửa máy", "The mechanic fixed my motorbike in an hour.", "Thợ sửa xe đã sửa xe máy của tôi trong một giờ."],
  ["electrician", "n", "ɪˌlekˈtrɪʃən", "thợ điện", "We need an electrician to fix the lights.", "Chúng tôi cần thợ điện để sửa đèn."],
  ["plumber", "n", "ˈplʌmɚ", "thợ sửa ống nước", "The plumber is coming to fix the sink.", "Thợ sửa ống nước sắp đến sửa bồn rửa."],
  ["chef", "n", "ʃef", "đầu bếp", "The chef at this restaurant is from Hue.", "Đầu bếp ở nhà hàng này đến từ Huế."],
  ["waiter", "n", "ˈweɪtɚ", "bồi bàn", "The waiter brought us some water.", "Anh bồi bàn mang nước cho chúng tôi."],
  ["receptionist", "n", "rɪˈsepʃənɪst", "lễ tân", "The receptionist gave me the room key.", "Lễ tân đưa cho tôi chìa khóa phòng."],
  ["cashier", "n", "kæˈʃɪr", "thu ngân", "Please pay the cashier at the front.", "Vui lòng thanh toán với thu ngân ở phía trước."],
  ["pilot", "n", "ˈpaɪlət", "phi công", "He wanted to be a pilot as a child.", "Hồi nhỏ anh ấy muốn làm phi công."],
  ["flight attendant", "n", "ˈflaɪt əˌtendənt", "tiếp viên hàng không", "The flight attendant helped me with my bag.", "Tiếp viên hàng không giúp tôi cất túi."],
  ["reporter", "n", "rɪˈpɔːrtɚ", "phóng viên", "A TV reporter asked me some questions.", "Một phóng viên truyền hình hỏi tôi vài câu."],
  ["photographer", "n", "fəˈtɑːɡrəfɚ", "nhiếp ảnh gia", "We hired a photographer for our wedding.", "Chúng tôi thuê một thợ chụp ảnh cho đám cưới."],
  ["designer", "n", "dɪˈzaɪnɚ", "nhà thiết kế", "She is a fashion designer in Saigon.", "Cô ấy là nhà thiết kế thời trang ở Sài Gòn."],
  ["programmer", "n", "ˈproʊɡræmɚ", "lập trình viên", "Many young people want to become programmers.", "Nhiều bạn trẻ muốn trở thành lập trình viên."],
  ["police officer", "n", "pəˈliːs ˌɑːfɪsɚ", "cảnh sát", "A police officer showed us the way.", "Một anh cảnh sát đã chỉ đường cho chúng tôi."],
  ["firefighter", "n", "ˈfaɪɚˌfaɪtɚ", "lính cứu hỏa", "The firefighters arrived very quickly.", "Lính cứu hỏa đến rất nhanh."],
  ["farmer", "n", "ˈfɑːrmɚ", "nông dân", "My grandfather was a rice farmer.", "Ông tôi từng là nông dân trồng lúa."],
  ["tour guide", "n", "ˈtʊr ɡaɪd", "hướng dẫn viên du lịch", "Our tour guide speaks three languages.", "Hướng dẫn viên của chúng tôi nói được ba thứ tiếng."],
  ["hairdresser", "n", "ˈherˌdresɚ", "thợ làm tóc", "My hairdresser always gives good advice.", "Thợ làm tóc của tôi luôn cho lời khuyên hay."],
  ["tailor", "n", "ˈteɪlɚ", "thợ may", "The tailor made this suit for me.", "Thợ may đã may bộ vest này cho tôi."],
  ["secretary", "n", "ˈsekrəteri", "thư ký", "The secretary will call you back.", "Thư ký sẽ gọi lại cho bạn."],
  ["librarian", "n", "laɪˈbreriən", "thủ thư", "The librarian helped me find the book.", "Cô thủ thư giúp tôi tìm cuốn sách."],
  ["salesperson", "n", "ˈseɪlzˌpɝːsən", "nhân viên bán hàng", "The salesperson showed me several phones.", "Nhân viên bán hàng cho tôi xem vài chiếc điện thoại."],
  ["security guard", "n", "sɪˈkjʊrəti ɡɑːrd", "bảo vệ", "The security guard checked my ID card.", "Bác bảo vệ kiểm tra thẻ căn cước của tôi."],
  ["scientist", "n", "ˈsaɪəntɪst", "nhà khoa học", "Scientists are studying the new virus.", "Các nhà khoa học đang nghiên cứu loại virus mới."],
  ["translator", "n", "trænsˈleɪtɚ", "biên dịch viên", "She works as a Japanese translator.", "Cô ấy làm biên dịch viên tiếng Nhật."],
  ["carpenter", "n", "ˈkɑːrpəntɚ", "thợ mộc", "A carpenter made this wooden table.", "Một người thợ mộc đã làm chiếc bàn gỗ này."],
  ["veterinarian", "n", "ˌvetɚəˈneriən", "bác sĩ thú y", "We took our sick dog to the veterinarian.", "Chúng tôi đưa chú chó bị ốm đến bác sĩ thú y."],
  ["soldier", "n", "ˈsoʊldʒɚ", "người lính", "His grandfather was a soldier in the war.", "Ông của anh ấy từng là lính trong chiến tranh."],
  ["career", "n", "kəˈrɪr", "sự nghiệp", "She wants a career in marketing.", "Cô ấy muốn theo sự nghiệp marketing."],
  ["intern", "n", "ˈɪntɝːn", "thực tập sinh", "He is an intern at a bank this summer.", "Mùa hè này anh ấy là thực tập sinh ở một ngân hàng."],
  ["builder", "n", "ˈbɪldɚ", "thợ xây", "The builders finished the house in six months.", "Thợ xây hoàn thành ngôi nhà trong sáu tháng."],
  ["painter", "n", "ˈpeɪntɚ", "thợ sơn, họa sĩ", "We hired a painter to paint the living room.", "Chúng tôi thuê thợ sơn để sơn phòng khách."],
  ["baker", "n", "ˈbeɪkɚ", "thợ làm bánh", "The baker starts work at four a.m.", "Thợ làm bánh bắt đầu làm việc lúc bốn giờ sáng."],
  ["cleaner", "n", "ˈkliːnɚ", "người dọn dẹp", "The cleaner comes to our office every evening.", "Người dọn dẹp đến văn phòng chúng tôi mỗi tối."],
]);

extendTopic("city", "Thành phố & địa điểm", [
  ["skyscraper", "n", "ˈskaɪˌskreɪpɚ", "tòa nhà chọc trời", "There are many new skyscrapers in Ho Chi Minh City.", "Có nhiều tòa nhà chọc trời mới ở Thành phố Hồ Chí Minh."],
  ["post office", "n", "ˈpoʊst ˌɑːfɪs", "bưu điện", "I need to send this package at the post office.", "Tôi cần gửi gói hàng này ở bưu điện."],
  ["bridge", "n", "brɪdʒ", "cây cầu", "The Dragon Bridge breathes fire on weekends.", "Cầu Rồng phun lửa vào cuối tuần."],
  ["crossroads", "n", "ˈkrɔːsroʊdz", "ngã tư", "Turn right at the next crossroads.", "Rẽ phải ở ngã tư tiếp theo."],
  ["market", "n", "ˈmɑːrkɪt", "chợ", "My mom goes to the market every morning.", "Mẹ tôi đi chợ mỗi sáng."],
  ["supermarket", "n", "ˈsuːpɚˌmɑːrkɪt", "siêu thị", "The supermarket is open until ten p.m.", "Siêu thị mở cửa đến mười giờ tối."],
  ["department store", "n", "dɪˈpɑːrtmənt stɔːr", "cửa hàng bách hóa", "The department store has five floors.", "Cửa hàng bách hóa có năm tầng."],
  ["bank", "n", "bæŋk", "ngân hàng", "The bank closes at four on Fridays.", "Ngân hàng đóng cửa lúc bốn giờ vào thứ Sáu."],
  ["library", "n", "ˈlaɪbreri", "thư viện", "I often study at the library.", "Tôi thường học ở thư viện."],
  ["museum", "n", "mjuːˈziːəm", "bảo tàng", "The museum is free on Sundays.", "Bảo tàng miễn phí vào Chủ nhật."],
  ["park", "n", "pɑːrk", "công viên", "People jog in the park every morning.", "Mọi người chạy bộ trong công viên mỗi sáng."],
  ["fountain", "n", "ˈfaʊntən", "đài phun nước", "Let's meet by the fountain in the park.", "Mình gặp nhau cạnh đài phun nước trong công viên nhé."],
  ["swimming pool", "n", "ˈswɪmɪŋ puːl", "hồ bơi", "There's a public swimming pool near my house.", "Có một hồ bơi công cộng gần nhà tôi."],
  ["bus stop", "n", "ˈbʌs stɑːp", "trạm xe buýt", "I waited at the bus stop for twenty minutes.", "Tôi đã đợi ở trạm xe buýt hai mươi phút."],
  ["train station", "n", "ˈtreɪn ˌsteɪʃən", "ga tàu", "The train station is in the city center.", "Ga tàu nằm ở trung tâm thành phố."],
  ["statue", "n", "ˈstætʃuː", "bức tượng", "There is a big statue in the city square.", "Có một bức tượng lớn ở quảng trường thành phố."],
  ["police station", "n", "pəˈliːs ˌsteɪʃən", "đồn cảnh sát", "He reported his lost wallet at the police station.", "Anh ấy trình báo mất ví ở đồn cảnh sát."],
  ["gas station", "n", "ˈɡæs ˌsteɪʃən", "cây xăng", "We need to stop at a gas station.", "Chúng ta cần ghé cây xăng."],
  ["parking lot", "n", "ˈpɑːrkɪŋ lɑːt", "bãi đỗ xe", "The parking lot behind the mall is free.", "Bãi đỗ xe phía sau trung tâm thương mại miễn phí."],
  ["sidewalk", "n", "ˈsaɪdwɔːk", "vỉa hè", "Many people sell food on the sidewalk.", "Nhiều người bán đồ ăn trên vỉa hè."],
  ["crosswalk", "n", "ˈkrɔːswɔːk", "vạch qua đường", "Always cross the street at the crosswalk.", "Luôn qua đường ở vạch dành cho người đi bộ."],
  ["traffic light", "n", "ˈtræfɪk laɪt", "đèn giao thông", "Stop when the traffic light is red.", "Dừng lại khi đèn giao thông chuyển đỏ."],
  ["street", "n", "striːt", "đường phố", "This street is always busy at night.", "Con phố này lúc nào cũng đông vào buổi tối."],
  ["alley", "n", "ˈæli", "hẻm, ngõ", "My house is at the end of this alley.", "Nhà tôi ở cuối con hẻm này."],
  ["corner", "n", "ˈkɔːrnɚ", "góc đường", "There's a small café on the corner.", "Có một quán cà phê nhỏ ở góc đường."],
  ["square", "n", "skwer", "quảng trường", "People gather in the square for New Year.", "Mọi người tụ tập ở quảng trường đón năm mới."],
  ["church", "n", "tʃɝːtʃ", "nhà thờ", "The old church is a popular tourist spot.", "Nhà thờ cổ là điểm du lịch nổi tiếng."],
  ["temple", "n", "ˈtempəl", "đền", "We visited an old temple in Hanoi.", "Chúng tôi đã thăm một ngôi đền cổ ở Hà Nội."],
  ["pagoda", "n", "pəˈɡoʊdə", "chùa", "My grandmother goes to the pagoda on full moon days.", "Bà tôi đi chùa vào các ngày rằm."],
  ["shopping mall", "n", "ˈʃɑːpɪŋ mɔːl", "trung tâm thương mại", "The new shopping mall has a big food court.", "Trung tâm thương mại mới có khu ẩm thực lớn."],
  ["restaurant", "n", "ˈrestərɑːnt", "nhà hàng", "This restaurant serves great seafood.", "Nhà hàng này có hải sản rất ngon."],
  ["coffee shop", "n", "ˈkɑːfi ʃɑːp", "quán cà phê", "We often work at a coffee shop.", "Chúng tôi hay làm việc ở quán cà phê."],
  ["bakery", "n", "ˈbeɪkɚi", "tiệm bánh", "The bakery sells fresh bread every morning.", "Tiệm bánh bán bánh mì mới mỗi sáng."],
  ["bookstore", "n", "ˈbʊkstɔːr", "hiệu sách", "I bought this novel at a bookstore downtown.", "Tôi mua cuốn tiểu thuyết này ở một hiệu sách trong trung tâm."],
  ["town hall", "n", "ˌtaʊn ˈhɑːl", "tòa thị chính", "The town hall is next to the post office.", "Tòa thị chính nằm cạnh bưu điện."],
  ["zoo", "n", "zuː", "sở thú", "The kids loved the elephants at the zoo.", "Bọn trẻ rất thích những con voi ở sở thú."],
  ["downtown", "adv", "ˌdaʊnˈtaʊn", "ở trung tâm thành phố", "We're going downtown for dinner tonight.", "Tối nay chúng tôi vào trung tâm thành phố ăn tối."],
  ["suburb", "n", "ˈsʌbɝːb", "vùng ngoại ô", "They moved to a quiet suburb.", "Họ chuyển đến một vùng ngoại ô yên tĩnh."],
  ["hotel", "n", "hoʊˈtel", "khách sạn", "Our hotel is close to the beach.", "Khách sạn của chúng tôi gần bãi biển."],
  ["city hall", "n", "ˌsɪti ˈhɑːl", "tòa thị chính", "The concert is in front of city hall.", "Buổi hòa nhạc diễn ra trước tòa thị chính."],
]);

extendTopic("verbs", "Động từ thông dụng", [
  ["pull", "v", "pʊl", "kéo", "Pull the door to open it.", "Kéo cửa để mở."],
  ["notice", "v", "ˈnoʊtɪs", "để ý, nhận thấy", "Did you notice anything different about me?", "Bạn có để ý thấy tôi có gì khác không?"],
  ["whisper", "v", "ˈwɪspɚ", "thì thầm", "She whispered something in my ear.", "Cô ấy thì thầm điều gì đó vào tai tôi."],
  ["forget", "v", "fɚˈɡet", "quên", "Don't forget to lock the door.", "Đừng quên khóa cửa nhé."],
  ["remember", "v", "rɪˈmembɚ", "nhớ", "I can't remember his name.", "Tôi không nhớ tên anh ấy."],
  ["decide", "v", "dɪˈsaɪd", "quyết định", "We decided to stay home tonight.", "Chúng tôi quyết định tối nay ở nhà."],
  ["agree", "v", "əˈɡriː", "đồng ý", "I agree with you completely.", "Tôi hoàn toàn đồng ý với bạn."],
  ["believe", "v", "bɪˈliːv", "tin", "I can't believe it's already Friday.", "Tôi không tin nổi đã thứ Sáu rồi."],
  ["choose", "v", "tʃuːz", "chọn", "You can choose any color you like.", "Bạn có thể chọn bất kỳ màu nào bạn thích."],
  ["carry", "v", "ˈkeri", "mang, xách", "Let me carry that bag for you.", "Để tôi xách cái túi đó giúp bạn."],
  ["compare", "v", "kəmˈper", "so sánh", "Compare the prices before you buy.", "Hãy so sánh giá trước khi mua."],
  ["describe", "v", "dɪˈskraɪb", "miêu tả", "Can you describe the man you saw?", "Bạn có thể miêu tả người đàn ông bạn đã thấy không?"],
  ["discuss", "v", "dɪˈskʌs", "thảo luận", "Let's discuss this after lunch.", "Mình thảo luận chuyện này sau bữa trưa nhé."],
  ["expect", "v", "ɪkˈspekt", "mong đợi", "I didn't expect so many people to come.", "Tôi không ngờ lại có nhiều người đến như vậy."],
  ["finish", "v", "ˈfɪnɪʃ", "hoàn thành, xong", "I'll call you when I finish work.", "Tôi sẽ gọi cho bạn khi làm xong việc."],
  ["follow", "v", "ˈfɑːloʊ", "đi theo, làm theo", "Follow me, I'll show you the way.", "Đi theo tôi, tôi sẽ chỉ đường cho bạn."],
  ["happen", "v", "ˈhæpən", "xảy ra", "What happened to your phone?", "Điện thoại của bạn bị làm sao vậy?"],
  ["hope", "v", "hoʊp", "hy vọng", "I hope you feel better soon.", "Mong bạn sớm khỏe lại."],
  ["repair", "v", "rɪˈper", "sửa chữa", "My dad can repair almost anything.", "Bố tôi có thể sửa gần như mọi thứ."],
  ["guess", "v", "ɡes", "đoán", "Guess who I saw at the market today!", "Đoán xem hôm nay mình gặp ai ở chợ!"],
  ["join", "v", "dʒɔɪn", "tham gia", "Would you like to join us for dinner?", "Bạn có muốn ăn tối cùng chúng tôi không?"],
  ["keep", "v", "kiːp", "giữ", "Please keep this seat for me.", "Làm ơn giữ chỗ này giúp tôi."],
  ["throw", "v", "θroʊ", "ném, quăng", "Please don't throw rubbish on the street.", "Làm ơn đừng vứt rác ra đường."],
  ["mention", "v", "ˈmenʃən", "nhắc đến", "She didn't mention the problem.", "Cô ấy không nhắc đến vấn đề đó."],
  ["miss", "v", "mɪs", "nhớ, lỡ", "I missed the bus this morning.", "Sáng nay tôi bị lỡ xe buýt."],
  ["prepare", "v", "prɪˈper", "chuẩn bị", "I need to prepare for the exam.", "Tôi cần chuẩn bị cho kỳ thi."],
  ["bring", "v", "brɪŋ", "mang theo, mang đến", "Don't forget to bring your umbrella.", "Đừng quên mang theo ô nhé."],
  ["prefer", "v", "prɪˈfɝː", "thích hơn", "I prefer tea to coffee.", "Tôi thích trà hơn cà phê."],
  ["realize", "v", "ˈriːəlaɪz", "nhận ra", "I didn't realize it was so late.", "Tôi không nhận ra đã muộn như vậy."],
  ["refuse", "v", "rɪˈfjuːz", "từ chối", "He refused to answer my question.", "Anh ấy từ chối trả lời câu hỏi của tôi."],
  ["repeat", "v", "rɪˈpiːt", "nhắc lại", "Could you repeat that, please?", "Bạn nhắc lại được không?"],
  ["answer", "v", "ˈænsɚ", "trả lời", "Nobody answered the phone.", "Không ai nghe máy cả."],
  ["leave", "v", "liːv", "rời đi, để lại", "What time do you leave home?", "Mấy giờ bạn ra khỏi nhà?"],
  ["accept", "v", "əkˈsept", "chấp nhận", "Do you accept credit cards?", "Ở đây có nhận thẻ tín dụng không?"],
  ["suggest", "v", "səɡˈdʒest", "gợi ý, đề xuất", "Can you suggest a good restaurant?", "Bạn gợi ý giúp mình một nhà hàng ngon được không?"],
  ["wait", "v", "weɪt", "chờ, đợi", "Wait for me at the entrance.", "Đợi tôi ở lối vào nhé."],
  ["allow", "v", "əˈlaʊ", "cho phép", "Smoking is not allowed here.", "Không được phép hút thuốc ở đây."],
  ["arrive", "v", "əˈraɪv", "đến nơi", "We arrived in Hanoi at midnight.", "Chúng tôi đến Hà Nội lúc nửa đêm."],
  ["avoid", "v", "əˈvɔɪd", "tránh", "Try to avoid the main road at rush hour.", "Cố tránh đường chính vào giờ cao điểm."],
  ["complain", "v", "kəmˈpleɪn", "phàn nàn", "He always complains about the food.", "Anh ấy lúc nào cũng phàn nàn về đồ ăn."],
]);

extendTopic("adjectives", "Tính từ thông dụng", [
  ["important", "adj", "ɪmˈpɔːrtənt", "quan trọng", "Sleep is very important for your health.", "Giấc ngủ rất quan trọng cho sức khỏe."],
  ["difficult", "adj", "ˈdɪfəkəlt", "khó", "This exercise is too difficult for me.", "Bài tập này quá khó với tôi."],
  ["easy", "adj", "ˈiːzi", "dễ", "The test was easier than I expected.", "Bài kiểm tra dễ hơn tôi nghĩ."],
  ["brave", "adj", "breɪv", "dũng cảm", "The brave boy saved his friend from the river.", "Cậu bé dũng cảm đã cứu bạn mình khỏi dòng sông."],
  ["similar", "adj", "ˈsɪməlɚ", "giống, tương tự", "Our jobs are quite similar.", "Công việc của chúng tôi khá giống nhau."],
  ["different", "adj", "ˈdɪfɚənt", "khác", "The two cities are very different.", "Hai thành phố rất khác nhau."],
  ["possible", "adj", "ˈpɑːsəbəl", "có thể", "Please reply as soon as possible.", "Vui lòng trả lời càng sớm càng tốt."],
  ["necessary", "adj", "ˈnesəseri", "cần thiết", "Is it necessary to bring my passport?", "Có cần mang theo hộ chiếu không?"],
  ["dangerous", "adj", "ˈdeɪndʒɚəs", "nguy hiểm", "It's dangerous to drive so fast.", "Lái xe nhanh như vậy rất nguy hiểm."],
  ["safe", "adj", "seɪf", "an toàn", "Is it safe to walk here at night?", "Đi bộ ở đây vào ban đêm có an toàn không?"],
  ["quiet", "adj", "ˈkwaɪət", "yên tĩnh", "I need a quiet place to study.", "Tôi cần một nơi yên tĩnh để học."],
  ["noisy", "adj", "ˈnɔɪzi", "ồn ào", "The street outside is very noisy.", "Con đường bên ngoài rất ồn ào."],
  ["crowded", "adj", "ˈkraʊdɪd", "đông đúc", "The beach is crowded on weekends.", "Bãi biển đông đúc vào cuối tuần."],
  ["empty", "adj", "ˈempti", "trống, rỗng", "The fridge is empty again.", "Tủ lạnh lại trống trơn rồi."],
  ["dirty", "adj", "ˈdɝːti", "bẩn", "Your shoes are dirty, take them off.", "Giày bạn bẩn rồi, cởi ra đi."],
  ["modern", "adj", "ˈmɑːdɚn", "hiện đại", "The new hospital looks very modern.", "Bệnh viện mới trông rất hiện đại."],
  ["famous", "adj", "ˈfeɪməs", "nổi tiếng", "Hoi An is famous for its lanterns.", "Hội An nổi tiếng với những chiếc đèn lồng."],
  ["popular", "adj", "ˈpɑːpjəlɚ", "phổ biến, được ưa chuộng", "This song is very popular with teenagers.", "Bài hát này rất được giới trẻ yêu thích."],
  ["common", "adj", "ˈkɑːmən", "phổ biến, thông thường", "Nguyen is a very common name in Vietnam.", "Nguyễn là họ rất phổ biến ở Việt Nam."],
  ["strange", "adj", "streɪndʒ", "lạ", "I heard a strange noise last night.", "Tối qua tôi nghe thấy một tiếng động lạ."],
  ["simple", "adj", "ˈsɪmpəl", "đơn giản", "The instructions are short and simple.", "Hướng dẫn ngắn gọn và đơn giản."],
  ["useful", "adj", "ˈjuːsfəl", "hữu ích", "This app is really useful for learning words.", "Ứng dụng này rất hữu ích để học từ vựng."],
  ["convenient", "adj", "kənˈviːniənt", "tiện lợi", "Is Monday morning convenient for you?", "Sáng thứ Hai có tiện cho bạn không?"],
  ["comfortable", "adj", "ˈkʌmftɚbəl", "thoải mái", "These shoes are very comfortable.", "Đôi giày này đi rất thoải mái."],
  ["correct", "adj", "kəˈrekt", "đúng, chính xác", "Your answer is correct.", "Câu trả lời của bạn đúng rồi."],
  ["wrong", "adj", "rɑːŋ", "sai", "Sorry, I think you have the wrong number.", "Xin lỗi, tôi nghĩ bạn gọi nhầm số rồi."],
  ["ready", "adj", "ˈredi", "sẵn sàng", "Dinner is ready!", "Cơm tối xong rồi!"],
  ["certain", "adj", "ˈsɝːtən", "chắc chắn", "Are you certain about the time?", "Bạn có chắc về giờ giấc không?"],
  ["available", "adj", "əˈveɪləbəl", "có sẵn, rảnh", "Is this room available tonight?", "Phòng này tối nay còn trống không?"],
  ["serious", "adj", "ˈsɪriəs", "nghiêm trọng, nghiêm túc", "Don't worry, it's nothing serious.", "Đừng lo, không có gì nghiêm trọng đâu."],
  ["special", "adj", "ˈspeʃəl", "đặc biệt", "Today is a special day for us.", "Hôm nay là một ngày đặc biệt với chúng tôi."],
  ["normal", "adj", "ˈnɔːrməl", "bình thường", "It's normal to feel tired after a long trip.", "Mệt sau một chuyến đi dài là chuyện bình thường."],
  ["huge", "adj", "hjuːdʒ", "khổng lồ, rất lớn", "They live in a huge house.", "Họ sống trong một ngôi nhà rất lớn."],
  ["tiny", "adj", "ˈtaɪni", "nhỏ xíu", "My first apartment was tiny.", "Căn hộ đầu tiên của tôi nhỏ xíu."],
  ["fast", "adj", "fæst", "nhanh", "The internet here is really fast.", "Mạng ở đây rất nhanh."],
  ["slow", "adj", "sloʊ", "chậm", "The service at this café is slow.", "Phục vụ ở quán cà phê này chậm."],
  ["curious", "adj", "ˈkjʊriəs", "tò mò", "Children are curious about everything.", "Trẻ con tò mò về mọi thứ."],
  ["whole", "adj", "hoʊl", "toàn bộ, cả", "I spent the whole day at home.", "Tôi ở nhà cả ngày."],
  ["main", "adj", "meɪn", "chính", "The main entrance is on Le Loi Street.", "Lối vào chính ở đường Lê Lợi."],
  ["clear", "adj", "klɪr", "rõ ràng", "Is everything clear to you?", "Mọi thứ đã rõ chưa bạn?"],
]);
