// Câu giao tiếp hằng ngày, câu giao tiếp khi đi làm & đi chơi, từ vựng giao tiếp & các mối quan hệ.
extendTopic("talk", "Câu giao tiếp hằng ngày", [
  ["How's it going?", "s", "", "Dạo này thế nào?", "A: How's it going? B: Pretty good, thanks!", "A: Dạo này thế nào? B: Khá ổn, cảm ơn nhé!"],
  ["Long time no see!", "s", "", "Lâu quá không gặp!", "A: Long time no see! B: I know! It's been ages.", "A: Lâu quá không gặp! B: Đúng thế! Lâu lắm rồi."],
  ["Nice to meet you.", "s", "", "Rất vui được gặp bạn.", "A: I'm Lan. Nice to meet you. B: Nice to meet you too.", "A: Mình là Lan. Rất vui được gặp bạn. B: Mình cũng rất vui được gặp bạn."],
  ["What's up?", "s", "", "Có gì mới không?", "A: Hey, what's up? B: Not much. Just relaxing.", "A: Này, có gì mới không? B: Không có gì. Chỉ đang nghỉ ngơi thôi."],
  ["How have you been?", "s", "", "Dạo này bạn thế nào?", "A: How have you been? B: Busy, but good.", "A: Dạo này bạn thế nào? B: Bận, nhưng ổn."],
  ["Good to see you again.", "s", "", "Vui được gặp lại bạn.", "A: Good to see you again. B: You too! You look great.", "A: Vui được gặp lại bạn. B: Mình cũng vậy! Trông bạn tuyệt lắm."],
  ["Thanks a lot.", "s", "", "Cảm ơn nhiều.", "A: Here's your umbrella. B: Thanks a lot.", "A: Ô của bạn đây. B: Cảm ơn nhiều."],
  ["I really appreciate it.", "s", "", "Tôi thật sự rất biết ơn.", "A: I'll drive you to the airport. B: I really appreciate it.", "A: Mình sẽ chở bạn ra sân bay. B: Mình thật sự rất biết ơn."],
  ["You're welcome.", "s", "", "Không có gì.", "A: Thanks for the coffee. B: You're welcome.", "A: Cảm ơn vì ly cà phê. B: Không có gì."],
  ["No problem.", "s", "", "Không sao đâu.", "A: Thanks for waiting. B: No problem.", "A: Cảm ơn vì đã đợi. B: Không sao đâu."],
  ["Don't mention it.", "s", "", "Có gì đâu mà.", "A: Thanks for helping me move. B: Don't mention it.", "A: Cảm ơn đã giúp mình chuyển nhà. B: Có gì đâu mà."],
  ["I'm so sorry.", "s", "", "Tôi rất xin lỗi.", "A: You stepped on my foot. B: Oh, I'm so sorry.", "A: Bạn giẫm lên chân tôi rồi. B: Ôi, tôi rất xin lỗi."],
  ["Sorry I'm late.", "s", "", "Xin lỗi, mình đến muộn.", "A: Sorry I'm late. B: That's OK. We just started.", "A: Xin lỗi, mình đến muộn. B: Không sao. Bọn mình vừa bắt đầu thôi."],
  ["My bad.", "s", "", "Lỗi của mình.", "A: You took my pen. B: Oops, my bad.", "A: Bạn cầm nhầm bút của mình rồi. B: Ối, lỗi của mình."],
  ["Don't worry about it.", "s", "", "Đừng bận tâm.", "A: Sorry I forgot to call. B: Don't worry about it.", "A: Xin lỗi mình quên gọi. B: Đừng bận tâm."],
  ["Excuse me.", "s", "", "Xin lỗi (cho tôi hỏi / cho tôi qua).", "A: Excuse me. Is this seat free? B: Yes, go ahead.", "A: Xin lỗi. Ghế này còn trống không? B: Còn, bạn cứ ngồi."],
  ["Could you help me?", "s", "", "Bạn giúp tôi được không?", "A: Could you help me? B: Sure. What do you need?", "A: Bạn giúp tôi được không? B: Chắc chắn rồi. Bạn cần gì?"],
  ["Can you give me a hand?", "s", "", "Bạn phụ mình một tay được không?", "A: Can you give me a hand? B: Of course.", "A: Bạn phụ mình một tay được không? B: Tất nhiên rồi."],
  ["Do you have a minute?", "s", "", "Bạn có rảnh một chút không?", "A: Do you have a minute? B: Sure. What's up?", "A: Bạn có rảnh một chút không? B: Có chứ. Chuyện gì thế?"],
  ["Could you say that again?", "s", "", "Bạn nói lại được không?", "A: Could you say that again? B: Sure. I said nine o'clock.", "A: Bạn nói lại được không? B: Được. Mình nói chín giờ."],
  ["What does this mean?", "s", "", "Cái này nghĩa là gì?", "A: What does this mean? B: It means exit.", "A: Cái này nghĩa là gì? B: Nó nghĩa là lối ra."],
  ["I agree with you.", "s", "", "Tôi đồng ý với bạn.", "A: This movie is too long. B: I agree with you.", "A: Phim này dài quá. B: Tôi đồng ý với bạn."],
  ["That's true.", "s", "", "Đúng thế.", "A: Prices are going up everywhere. B: That's true.", "A: Giá cả chỗ nào cũng tăng. B: Đúng thế."],
  ["Sounds good.", "s", "", "Nghe được đấy.", "A: Let's meet at six. B: Sounds good.", "A: Mình gặp nhau lúc sáu giờ nhé. B: Nghe được đấy."],
  ["Exactly!", "s", "", "Chính xác!", "A: We need more time. B: Exactly!", "A: Chúng ta cần thêm thời gian. B: Chính xác!"],
  ["I'm not so sure.", "s", "", "Tôi không chắc lắm.", "A: It won't rain today. B: Hmm, I'm not so sure.", "A: Hôm nay sẽ không mưa đâu. B: Hừm, tôi không chắc lắm."],
  ["Good idea!", "s", "", "Ý hay đấy!", "A: Let's order pizza. B: Good idea!", "A: Gọi pizza đi. B: Ý hay đấy!"],
  ["Nice weather today, isn't it?", "s", "", "Hôm nay trời đẹp nhỉ?", "A: Nice weather today, isn't it? B: Yes, it's lovely.", "A: Hôm nay trời đẹp nhỉ? B: Ừ, dễ chịu quá."],
  ["Where are you from?", "s", "", "Bạn đến từ đâu?", "A: Where are you from? B: I'm from Hue.", "A: Bạn đến từ đâu? B: Mình đến từ Huế."],
  ["What do you do?", "s", "", "Bạn làm nghề gì?", "A: What do you do? B: I'm a nurse.", "A: Bạn làm nghề gì? B: Mình là y tá."],
  ["Any plans for the weekend?", "s", "", "Cuối tuần có kế hoạch gì không?", "A: Any plans for the weekend? B: I'm going to the beach.", "A: Cuối tuần có kế hoạch gì không? B: Mình đi biển."],
  ["How was your day?", "s", "", "Hôm nay của bạn thế nào?", "A: How was your day? B: Long, but not bad.", "A: Hôm nay của bạn thế nào? B: Dài, nhưng cũng không tệ."],
  ["That sounds fun!", "s", "", "Nghe vui đấy!", "A: We're going camping. B: That sounds fun!", "A: Bọn mình sẽ đi cắm trại. B: Nghe vui đấy!"],
  ["Really? I didn't know that.", "s", "", "Thật á? Mình không biết đấy.", "A: Tom is moving to Hanoi. B: Really? I didn't know that.", "A: Tom sắp chuyển ra Hà Nội. B: Thật á? Mình không biết đấy."],
  ["See you later.", "s", "", "Gặp lại sau nhé.", "A: I have to go now. B: OK, see you later.", "A: Mình phải đi bây giờ. B: Ừ, gặp lại sau nhé."],
  ["Take care.", "s", "", "Bảo trọng nhé.", "A: Bye! Take care. B: You too.", "A: Tạm biệt! Bảo trọng nhé. B: Bạn cũng vậy."],
  ["Have a nice day!", "s", "", "Chúc một ngày tốt lành!", "A: Have a nice day! B: Thanks, you too!", "A: Chúc một ngày tốt lành! B: Cảm ơn, bạn cũng vậy nhé!"],
  ["I'd better get going.", "s", "", "Mình phải đi thôi.", "A: It's late. I'd better get going. B: OK. Get home safe.", "A: Muộn rồi. Mình phải đi thôi. B: Ừ. Về nhà cẩn thận nhé."],
  ["Keep in touch!", "s", "", "Giữ liên lạc nhé!", "A: Keep in touch! B: I will. I'll text you.", "A: Giữ liên lạc nhé! B: Chắc chắn rồi. Mình sẽ nhắn tin cho bạn."],
  ["Say hi to your family.", "s", "", "Cho mình gửi lời hỏi thăm gia đình bạn.", "A: Say hi to your family. B: I will. Thanks!", "A: Cho mình gửi lời hỏi thăm gia đình bạn. B: Mình sẽ chuyển lời. Cảm ơn nhé!"],
]);

extendTopic("talk2", "Câu giao tiếp khi đi làm & đi chơi", [
  ["A table for two, please.", "s", "", "Cho tôi một bàn hai người.", "A: A table for two, please. B: Sure. Follow me.", "A: Cho tôi một bàn hai người. B: Vâng. Mời anh chị đi theo tôi."],
  ["Can I see the menu?", "s", "", "Cho tôi xem thực đơn được không?", "A: Can I see the menu? B: Here you are.", "A: Cho tôi xem thực đơn được không? B: Của anh đây ạ."],
  ["I'd like to order, please.", "s", "", "Tôi muốn gọi món.", "A: I'd like to order, please. B: Sure. What would you like?", "A: Tôi muốn gọi món. B: Vâng. Anh muốn dùng gì ạ?"],
  ["What do you recommend?", "s", "", "Bạn gợi ý món nào?", "A: What do you recommend? B: The grilled fish is great.", "A: Bạn gợi ý món nào? B: Món cá nướng rất ngon ạ."],
  ["Could I get an iced coffee?", "s", "", "Cho tôi một ly cà phê đá nhé?", "A: Could I get an iced coffee? B: Sure. Anything else?", "A: Cho tôi một ly cà phê đá nhé? B: Vâng. Anh cần gì nữa không ạ?"],
  ["For here or to go?", "s", "", "Dùng tại chỗ hay mang đi?", "A: For here or to go? B: To go, please.", "A: Dùng tại chỗ hay mang đi ạ? B: Mang đi nhé."],
  ["Can we have the check, please?", "s", "", "Cho chúng tôi tính tiền nhé.", "A: Can we have the check, please? B: Of course. One moment.", "A: Cho chúng tôi tính tiền nhé. B: Vâng. Chờ một chút ạ."],
  ["Keep the change.", "s", "", "Khỏi thối lại.", "A: Here's your change. B: Keep the change.", "A: Tiền thối của anh đây. B: Khỏi thối lại."],
  ["I'm just looking, thanks.", "s", "", "Tôi chỉ xem thôi, cảm ơn.", "A: Can I help you? B: I'm just looking, thanks.", "A: Tôi giúp gì được cho chị? B: Tôi chỉ xem thôi, cảm ơn."],
  ["How much is this?", "s", "", "Cái này bao nhiêu tiền?", "A: How much is this? B: It's twenty dollars.", "A: Cái này bao nhiêu tiền? B: Hai mươi đô ạ."],
  ["Do you have this in medium?", "s", "", "Cái này có cỡ M không?", "A: Do you have this in medium? B: Let me check.", "A: Cái này có cỡ M không? B: Để tôi kiểm tra."],
  ["Can I pay by card?", "s", "", "Tôi trả bằng thẻ được không?", "A: Can I pay by card? B: Yes, of course.", "A: Tôi trả bằng thẻ được không? B: Được chứ ạ."],
  ["Can you give me a discount?", "s", "", "Bớt cho tôi một chút được không?", "A: Can you give me a discount? B: OK, ten percent off.", "A: Bớt cho tôi một chút được không? B: Được, giảm mười phần trăm."],
  ["I'll take it.", "s", "", "Tôi lấy cái này.", "A: It's on sale today. B: Great. I'll take it.", "A: Hôm nay món này đang giảm giá. B: Tuyệt. Tôi lấy cái này."],
  ["How do I get to the station?", "s", "", "Đi đến nhà ga thế nào?", "A: How do I get to the station? B: Go straight and turn right.", "A: Đi đến nhà ga thế nào? B: Đi thẳng rồi rẽ phải."],
  ["Is it far from here?", "s", "", "Có xa đây không?", "A: Is it far from here? B: No, it's a five-minute walk.", "A: Có xa đây không? B: Không, đi bộ năm phút thôi."],
  ["I think I'm lost.", "s", "", "Hình như tôi bị lạc rồi.", "A: I think I'm lost. B: Where are you trying to go?", "A: Hình như tôi bị lạc rồi. B: Bạn đang muốn đi đâu?"],
  ["Is there an ATM nearby?", "s", "", "Gần đây có cây ATM không?", "A: Is there an ATM nearby? B: Yes, next to the bank.", "A: Gần đây có cây ATM không? B: Có, cạnh ngân hàng."],
  ["I have a reservation.", "s", "", "Tôi đã đặt phòng trước.", "A: I have a reservation. B: May I have your name?", "A: Tôi đã đặt phòng trước. B: Cho tôi xin tên của anh?"],
  ["What time is checkout?", "s", "", "Mấy giờ trả phòng?", "A: What time is checkout? B: At noon.", "A: Mấy giờ trả phòng? B: Lúc mười hai giờ trưa."],
  ["Is breakfast included?", "s", "", "Có bao gồm bữa sáng không?", "A: Is breakfast included? B: Yes, from six to ten.", "A: Có bao gồm bữa sáng không? B: Có, từ sáu đến mười giờ."],
  ["Where do I check in?", "s", "", "Tôi làm thủ tục ở đâu?", "A: Where do I check in? B: At counter twelve.", "A: Tôi làm thủ tục ở đâu? B: Ở quầy số mười hai."],
  ["Can I have a window seat?", "s", "", "Cho tôi ghế cạnh cửa sổ được không?", "A: Can I have a window seat? B: Sure, no problem.", "A: Cho tôi ghế cạnh cửa sổ được không? B: Được ạ, không vấn đề gì."],
  ["My flight has been delayed.", "s", "", "Chuyến bay của tôi bị hoãn.", "A: My flight has been delayed. B: Oh no! For how long?", "A: Chuyến bay của tôi bị hoãn. B: Ôi không! Hoãn bao lâu?"],
  ["Where is gate five?", "s", "", "Cổng số năm ở đâu?", "A: Where is gate five? B: Go upstairs and turn left.", "A: Cổng số năm ở đâu? B: Đi lên tầng rồi rẽ trái."],
  ["Let's get started.", "s", "", "Chúng ta bắt đầu nhé.", "A: Is everyone here? B: Yes. Let's get started.", "A: Mọi người đến đủ chưa? B: Đủ rồi. Chúng ta bắt đầu nhé."],
  ["Can I ask a question?", "s", "", "Tôi hỏi một câu được không?", "A: Can I ask a question? B: Sure, go ahead.", "A: Tôi hỏi một câu được không? B: Được, bạn cứ hỏi."],
  ["I'll get back to you.", "s", "", "Tôi sẽ phản hồi lại bạn sau.", "A: When can you finish it? B: I'll get back to you.", "A: Khi nào bạn làm xong? B: Tôi sẽ phản hồi lại bạn sau."],
  ["Let me check my schedule.", "s", "", "Để tôi xem lịch đã.", "A: Are you free Friday? B: Let me check my schedule.", "A: Thứ Sáu bạn rảnh không? B: Để tôi xem lịch đã."],
  ["Could you send me the file?", "s", "", "Bạn gửi tôi tập tin được không?", "A: Could you send me the file? B: Sure, I'll email it.", "A: Bạn gửi tôi tập tin được không? B: Được, tôi sẽ gửi email."],
  ["I'm running a bit late.", "s", "", "Tôi sẽ đến trễ một chút.", "A: I'm running a bit late. B: No worries. We'll wait.", "A: Tôi sẽ đến trễ một chút. B: Không sao. Chúng tôi sẽ đợi."],
  ["Good job, everyone.", "s", "", "Mọi người làm tốt lắm.", "A: We finished the project! B: Good job, everyone.", "A: Chúng ta xong dự án rồi! B: Mọi người làm tốt lắm."],
  ["Who's calling, please?", "s", "", "Xin hỏi ai đang gọi ạ?", "A: Who's calling, please? B: This is Minh from ABC.", "A: Xin hỏi ai đang gọi ạ? B: Tôi là Minh bên ABC."],
  ["Can I speak to Mr. Nam?", "s", "", "Cho tôi gặp anh Nam được không?", "A: Can I speak to Mr. Nam? B: Sorry, he's out.", "A: Cho tôi gặp anh Nam được không? B: Xin lỗi, anh ấy ra ngoài rồi."],
  ["Hold on a second.", "s", "", "Chờ một chút nhé.", "A: Is Mai there? B: Hold on a second.", "A: Mai có đó không? B: Chờ một chút nhé."],
  ["Can I leave a message?", "s", "", "Tôi để lại lời nhắn được không?", "A: She's not here. B: Can I leave a message?", "A: Cô ấy không có ở đây. B: Tôi để lại lời nhắn được không?"],
  ["Sorry, you're breaking up.", "s", "", "Xin lỗi, tiếng bị ngắt quãng.", "A: Can you hear me? B: Sorry, you're breaking up.", "A: Bạn nghe tôi không? B: Xin lỗi, tiếng bị ngắt quãng."],
  ["I'll call you back.", "s", "", "Tôi sẽ gọi lại cho bạn.", "A: Are you busy? B: Yes. I'll call you back.", "A: Bạn đang bận à? B: Ừ. Tôi sẽ gọi lại cho bạn."],
  ["Is this seat taken?", "s", "", "Ghế này có ai ngồi chưa?", "A: Is this seat taken? B: No, go ahead.", "A: Ghế này có ai ngồi chưa? B: Chưa, bạn cứ ngồi."],
  ["Could you take our photo?", "s", "", "Bạn chụp giúp chúng tôi tấm ảnh nhé?", "A: Could you take our photo? B: Sure. Say cheese!", "A: Bạn chụp giúp chúng tôi tấm ảnh nhé? B: Được thôi. Cười lên nào!"],
]);

extendTopic("social", "Giao tiếp & các mối quan hệ", [
  ["invite", "v", "ɪnˈvaɪt", "mời", "She invited me to her birthday party.", "Cô ấy mời tôi đến tiệc sinh nhật của cô ấy."],
  ["invitation", "n", "ˌɪnvəˈteɪʃən", "lời mời, thiệp mời", "Thanks for the invitation, but I'm busy.", "Cảm ơn lời mời, nhưng tôi bận rồi."],
  ["apologize", "v", "əˈpɑːlədʒaɪz", "xin lỗi", "He apologized for being late.", "Anh ấy xin lỗi vì đến muộn."],
  ["compliment", "n", "ˈkɑːmpləmənt", "lời khen", "She gave me a nice compliment on my dress.", "Cô ấy khen chiếc váy của tôi."],
  ["relationship", "n", "rɪˈleɪʃənʃɪp", "mối quan hệ", "I have a good relationship with my boss.", "Tôi có mối quan hệ tốt với sếp."],
  ["argue", "v", "ˈɑːrɡjuː", "cãi nhau, tranh cãi", "They often argue about money.", "Họ hay cãi nhau về chuyện tiền bạc."],
  ["trust", "v", "trʌst", "tin tưởng", "You can trust him. He never lies.", "Bạn có thể tin anh ấy. Anh ấy không bao giờ nói dối."],
  ["gossip", "v", "ˈɡɑːsəp", "buôn chuyện, nói xấu sau lưng", "Please don't gossip about your coworkers.", "Làm ơn đừng buôn chuyện về đồng nghiệp."],
  ["introduce", "v", "ˌɪntrəˈduːs", "giới thiệu", "Let me introduce you to my friend Hoa.", "Để mình giới thiệu bạn với Hoa, bạn mình."],
  ["stranger", "n", "ˈstreɪndʒɚ", "người lạ", "Don't get into a car with a stranger.", "Đừng lên xe người lạ."],
  ["acquaintance", "n", "əˈkweɪntəns", "người quen", "He's not a close friend, just an acquaintance.", "Anh ấy không phải bạn thân, chỉ là người quen."],
  ["greet", "v", "ɡriːt", "chào hỏi, đón chào", "She greeted us with a big smile.", "Cô ấy chào chúng tôi bằng một nụ cười tươi."],
  ["chat", "v", "tʃæt", "trò chuyện, tán gẫu", "We chatted for hours at the café.", "Chúng tôi tán gẫu hàng giờ ở quán cà phê."],
  ["respect", "v", "rɪˈspekt", "tôn trọng", "We should respect other people's opinions.", "Chúng ta nên tôn trọng ý kiến của người khác."],
  ["support", "v", "səˈpɔːrt", "ủng hộ, hỗ trợ", "My friends always support me.", "Bạn bè luôn ủng hộ tôi."],
  ["advice", "n", "ədˈvaɪs", "lời khuyên", "Can you give me some advice?", "Bạn cho mình vài lời khuyên được không?"],
  ["forgive", "v", "fɚˈɡɪv", "tha thứ", "Please forgive me. I made a mistake.", "Xin hãy tha thứ cho tôi. Tôi đã mắc lỗi."],
  ["promise", "v", "ˈprɑːmɪs", "hứa", "I promise I'll call you tonight.", "Mình hứa tối nay sẽ gọi cho bạn."],
  ["disagree", "v", "ˌdɪsəˈɡriː", "không đồng ý", "I disagree with you on this point.", "Tôi không đồng ý với bạn ở điểm này."],
  ["misunderstand", "v", "ˌmɪsʌndɚˈstænd", "hiểu lầm", "Sorry, I misunderstood your message.", "Xin lỗi, tôi hiểu lầm tin nhắn của bạn."],
  ["rumor", "n", "ˈruːmɚ", "tin đồn", "Don't believe that rumor. It isn't true.", "Đừng tin tin đồn đó. Nó không đúng đâu."],
  ["break up", "phr", "breɪk ˈʌp", "chia tay", "They broke up after three years.", "Họ chia tay sau ba năm."],
  ["fall out", "phr", "fɑːl ˈaʊt", "cãi nhau, bất hòa", "I fell out with my roommate last week.", "Tuần trước tôi cãi nhau với bạn cùng phòng."],
  ["make up", "phr", "meɪk ˈʌp", "làm lành", "They argued, but they made up the next day.", "Họ cãi nhau, nhưng hôm sau đã làm lành."],
  ["hang out", "phr", "hæŋ ˈaʊt", "đi chơi, tụ tập", "Do you want to hang out this weekend?", "Cuối tuần này bạn muốn đi chơi không?"],
  ["get to know", "phr", "ɡet tə ˈnoʊ", "làm quen, tìm hiểu", "I'd like to get to know you better.", "Mình muốn hiểu bạn hơn."],
  ["secret", "n", "ˈsiːkrət", "bí mật", "Can you keep a secret?", "Bạn giữ bí mật được không?"],
  ["shake hands", "phr", "ʃeɪk ˈhændz", "bắt tay", "They shook hands and sat down.", "Họ bắt tay rồi ngồi xuống."],
  ["favor", "n", "ˈfeɪvɚ", "việc giúp đỡ, ân huệ", "Can you do me a favor?", "Bạn giúp mình một việc được không?"],
  ["encourage", "v", "ɪnˈkɝːɪdʒ", "khuyến khích, động viên", "My teacher encouraged me to study abroad.", "Thầy giáo khuyến khích tôi đi du học."],
  ["criticize", "v", "ˈkrɪtəsaɪz", "chỉ trích, phê bình", "He always criticizes my cooking.", "Anh ấy lúc nào cũng chê tôi nấu ăn."],
  ["blame", "v", "bleɪm", "đổ lỗi", "Don't blame me. It wasn't my fault.", "Đừng đổ lỗi cho tôi. Đó không phải lỗi của tôi."],
  ["interrupt", "v", "ˌɪntəˈrʌpt", "ngắt lời", "Sorry to interrupt, but I have a question.", "Xin lỗi đã ngắt lời, nhưng tôi có một câu hỏi."],
  ["polite", "adj", "pəˈlaɪt", "lịch sự", "It's polite to say thank you.", "Nói cảm ơn là lịch sự."],
  ["rude", "adj", "ruːd", "thô lỗ, bất lịch sự", "It's rude to use your phone at dinner.", "Dùng điện thoại trong bữa ăn là bất lịch sự."],
  ["guest", "n", "ɡest", "khách", "We have some guests coming for dinner.", "Nhà mình có vài vị khách đến ăn tối."],
  ["host", "n", "hoʊst", "chủ nhà, người tổ chức", "The host welcomed everyone at the door.", "Chủ nhà đón mọi người ở cửa."],
  ["date", "n", "deɪt", "buổi hẹn hò", "They went on a date to the cinema.", "Họ hẹn hò đi xem phim."],
  ["reply", "v", "rɪˈplaɪ", "trả lời, hồi âm", "She didn't reply to my message.", "Cô ấy không trả lời tin nhắn của tôi."],
  ["celebrate", "v", "ˈseləbreɪt", "ăn mừng, tổ chức", "Let's celebrate your new job tonight!", "Tối nay mình ăn mừng công việc mới của bạn nhé!"],
]);
