extendTopic("media", "Phim ảnh, âm nhạc & tin tức", [
  ["episode", "n", "ˈepəsoʊd", "tập (phim)", "I watched three episodes last night.", "Tối qua tôi xem ba tập phim."],
  ["series", "n", "ˈsɪriːz", "loạt phim, phim bộ", "This Korean series has sixteen episodes.", "Bộ phim Hàn này có mười sáu tập."],
  ["movie theater", "n", "ˈmuːvi ˌθiːətɚ", "rạp chiếu phim", "Let's meet at the movie theater at seven.", "Hẹn gặp ở rạp chiếu phim lúc bảy giờ nhé."],
  ["actor", "n", "ˈæktɚ", "nam diễn viên", "He is my favorite actor.", "Anh ấy là nam diễn viên tôi thích nhất."],
  ["actress", "n", "ˈæktrəs", "nữ diễn viên", "The actress won an award this year.", "Nữ diễn viên đó đã giành giải thưởng năm nay."],
  ["director", "n", "dəˈrektɚ", "đạo diễn", "The director made a very funny movie.", "Đạo diễn đã làm một bộ phim rất hài hước."],
  ["trailer", "n", "ˈtreɪlɚ", "đoạn giới thiệu phim", "The trailer looks really exciting.", "Đoạn giới thiệu phim trông rất hấp dẫn."],
  ["subtitles", "n", "ˈsʌbˌtaɪtəlz", "phụ đề", "I watch English movies with subtitles.", "Tôi xem phim tiếng Anh có phụ đề."],
  ["plot", "n", "plɑːt", "cốt truyện", "The plot was hard to follow.", "Cốt truyện khó theo dõi quá."],
  ["ending", "n", "ˈendɪŋ", "cái kết", "I didn't like the ending of the movie.", "Tôi không thích cái kết của bộ phim."],
  ["scene", "n", "siːn", "cảnh (phim)", "The last scene made me cry.", "Cảnh cuối làm tôi khóc."],
  ["character", "n", "ˈkerəktɚ", "nhân vật", "Who is your favorite character?", "Nhân vật bạn thích nhất là ai?"],
  ["comedy", "n", "ˈkɑːmədi", "phim hài", "Let's watch a comedy tonight.", "Tối nay mình xem phim hài đi."],
  ["horror movie", "n", "ˈhɔːrɚ ˌmuːvi", "phim kinh dị", "I can't watch horror movies alone.", "Tôi không dám xem phim kinh dị một mình."],
  ["cartoon", "n", "kɑːrˈtuːn", "phim hoạt hình", "My son watches cartoons every morning.", "Con trai tôi xem phim hoạt hình mỗi sáng."],
  ["documentary", "n", "ˌdɑːkjəˈmentɚi", "phim tài liệu", "We watched a documentary about the ocean.", "Chúng tôi đã xem một phim tài liệu về đại dương."],
  ["song", "n", "sɔːŋ", "bài hát", "This song is very popular right now.", "Bài hát này đang rất nổi tiếng."],
  ["singer", "n", "ˈsɪŋɚ", "ca sĩ", "She wants to become a singer.", "Cô ấy muốn trở thành ca sĩ."],
  ["band", "n", "bænd", "ban nhạc", "My brother plays guitar in a band.", "Anh tôi chơi guitar trong một ban nhạc."],
  ["album", "n", "ˈælbəm", "album nhạc", "Their new album comes out next week.", "Album mới của họ ra mắt vào tuần sau."],
  ["lyrics", "n", "ˈlɪrɪks", "lời bài hát", "I don't understand the lyrics of this song.", "Tôi không hiểu lời bài hát này."],
  ["concert", "n", "ˈkɑːnsɚt", "buổi hòa nhạc", "We went to a concert last Saturday.", "Thứ Bảy tuần trước chúng tôi đi xem hòa nhạc."],
  ["playlist", "n", "ˈpleɪlɪst", "danh sách phát", "I made a playlist for the road trip.", "Tôi đã tạo một danh sách nhạc cho chuyến đi."],
  ["podcast", "n", "ˈpɑːdkæst", "podcast (chương trình âm thanh)", "I listen to a podcast on my way to work.", "Tôi nghe podcast trên đường đi làm."],
  ["channel", "n", "ˈtʃænəl", "kênh", "What channel is the game on?", "Trận đấu chiếu trên kênh nào?"],
  ["audience", "n", "ˈɑːdiəns", "khán giả", "The audience loved the show.", "Khán giả rất thích buổi diễn."],
  ["stream", "v", "striːm", "phát trực tuyến, xem trực tuyến", "You can stream the movie online.", "Bạn có thể xem bộ phim trực tuyến."],
  ["subscribe", "v", "səbˈskraɪb", "đăng ký theo dõi", "Please subscribe to my channel.", "Hãy đăng ký kênh của tôi nhé."],
  ["blog", "n", "blɑːɡ", "blog, trang nhật ký cá nhân trên mạng", "She writes a blog about Vietnamese food.", "Cô ấy viết blog về ẩm thực Việt Nam."],
  ["hashtag", "n", "ˈhæʃtæɡ", "thẻ bắt đầu bằng dấu #", "Add a hashtag so more people can find your post.", "Thêm hashtag để nhiều người tìm thấy bài đăng của bạn hơn."],
  ["comment", "n", "ˈkɑːment", "bình luận", "Thanks for all your nice comments.", "Cảm ơn mọi người vì những bình luận dễ thương."],
  ["follower", "n", "ˈfɑːloʊɚ", "người theo dõi", "He has over ten thousand followers.", "Anh ấy có hơn mười nghìn người theo dõi."],
  ["go viral", "phr", "ˌɡoʊ ˈvaɪrəl", "lan truyền nhanh, nổi rần rần", "Her dance video went viral overnight.", "Video nhảy của cô ấy nổi rần rần chỉ sau một đêm."],
  ["headline", "n", "ˈhedlaɪn", "tiêu đề báo", "I only read the headlines in the morning.", "Buổi sáng tôi chỉ đọc các tiêu đề báo."],
  ["article", "n", "ˈɑːrtɪkəl", "bài báo", "I read an interesting article about coffee.", "Tôi đã đọc một bài báo thú vị về cà phê."],
  ["journalist", "n", "ˈdʒɝːnəlɪst", "nhà báo", "The journalist asked the mayor a question.", "Nhà báo đã đặt câu hỏi cho thị trưởng."],
  ["newspaper", "n", "ˈnuːzˌpeɪpɚ", "báo, tờ báo", "My grandfather reads the newspaper every morning.", "Ông tôi đọc báo mỗi sáng."],
  ["advertisement", "n", "ˌædvɚˈtaɪzmənt", "quảng cáo", "There are too many advertisements on TV.", "Trên tivi có quá nhiều quảng cáo."],
  ["fake news", "n", "ˌfeɪk ˈnuːz", "tin giả", "Don't share fake news on Facebook.", "Đừng chia sẻ tin giả trên Facebook."],
  ["spoiler", "n", "ˈspɔɪlɚ", "tiết lộ nội dung phim", "No spoilers, please! I haven't seen it yet.", "Đừng tiết lộ nhé! Tôi chưa xem mà."],
]);

extendTopic("business", "Kinh doanh & email công việc", [
  ["owner", "n", "ˈoʊnɚ", "chủ, người sở hữu", "The owner of the shop is very friendly.", "Chủ cửa hàng rất thân thiện."],
  ["competitor", "n", "kəmˈpetətɚ", "đối thủ cạnh tranh", "Our main competitor has lower prices.", "Đối thủ cạnh tranh chính của chúng tôi có giá thấp hơn."],
  ["invoice", "n", "ˈɪnvɔɪs", "hóa đơn", "Please send me the invoice by Friday.", "Vui lòng gửi tôi hóa đơn trước thứ Sáu."],
  ["proposal", "n", "prəˈpoʊzəl", "đề xuất, bản đề xuất", "The boss liked my proposal.", "Sếp thích bản đề xuất của tôi."],
  ["attach", "v", "əˈtætʃ", "đính kèm", "I have attached the file to this email.", "Tôi đã đính kèm tệp vào email này."],
  ["attachment", "n", "əˈtætʃmənt", "tệp đính kèm", "I can't open the attachment.", "Tôi không mở được tệp đính kèm."],
  ["confirm", "v", "kənˈfɝːm", "xác nhận", "Could you confirm the time of the meeting?", "Anh có thể xác nhận thời gian cuộc họp không?"],
  ["schedule a call", "phr", "ˈskedʒuːl ə ˈkɑːl", "hẹn lịch gọi điện", "Let's schedule a call for next Monday.", "Mình hẹn lịch gọi vào thứ Hai tuần sau nhé."],
  ["profit", "n", "ˈprɑːfɪt", "lợi nhuận", "Our profit went up this year.", "Lợi nhuận của chúng tôi tăng trong năm nay."],
  ["loss", "n", "lɔːs", "khoản lỗ, thua lỗ", "The shop made a loss last month.", "Cửa hàng bị lỗ vào tháng trước."],
  ["revenue", "n", "ˈrevənuː", "doanh thu", "Our revenue doubled in two years.", "Doanh thu của chúng tôi tăng gấp đôi trong hai năm."],
  ["income", "n", "ˈɪnkʌm", "thu nhập", "Their income has increased this year.", "Thu nhập của họ đã tăng trong năm nay."],
  ["expense", "n", "ɪkˈspens", "khoản chi tiêu, chi phí", "Rent is our biggest expense.", "Tiền thuê nhà là khoản chi lớn nhất của chúng tôi."],
  ["sales", "n", "seɪlz", "doanh số; bộ phận kinh doanh", "Sales were very good in December.", "Doanh số tháng Mười Hai rất tốt."],
  ["product", "n", "ˈprɑːdʌkt", "sản phẩm", "Our new product is selling well.", "Sản phẩm mới của chúng tôi đang bán chạy."],
  ["service", "n", "ˈsɝːvɪs", "dịch vụ", "They offer a delivery service.", "Họ có dịch vụ giao hàng."],
  ["startup", "n", "ˈstɑːrtʌp", "công ty khởi nghiệp", "He works for a small tech startup.", "Anh ấy làm cho một công ty khởi nghiệp công nghệ nhỏ."],
  ["manager", "n", "ˈmænɪdʒɚ", "quản lý", "I need to ask my manager first.", "Tôi cần hỏi quản lý trước đã."],
  ["department", "n", "dɪˈpɑːrtmənt", "phòng, ban", "She works in the marketing department.", "Cô ấy làm ở phòng marketing."],
  ["headquarters", "n", "ˈhedˌkwɔːrtɚz", "trụ sở chính", "The company's headquarters is in Hanoi.", "Trụ sở chính của công ty ở Hà Nội."],
  ["supplier", "n", "səˈplaɪɚ", "nhà cung cấp", "We are looking for a cheaper supplier.", "Chúng tôi đang tìm nhà cung cấp rẻ hơn."],
  ["partner", "n", "ˈpɑːrtnɚ", "đối tác", "They are our business partner in Japan.", "Họ là đối tác kinh doanh của chúng tôi ở Nhật."],
  ["negotiate", "v", "nəˈɡoʊʃieɪt", "đàm phán, thương lượng", "We negotiated a better price.", "Chúng tôi đã thương lượng được giá tốt hơn."],
  ["deal", "n", "diːl", "thỏa thuận, hợp đồng làm ăn", "We finally made a deal with them.", "Cuối cùng chúng tôi đã đạt được thỏa thuận với họ."],
  ["sign", "v", "saɪn", "ký", "Please sign here and here.", "Vui lòng ký vào chỗ này và chỗ này."],
  ["payment", "n", "ˈpeɪmənt", "khoản thanh toán", "We haven't received your payment yet.", "Chúng tôi chưa nhận được khoản thanh toán của anh."],
  ["quote", "n", "kwoʊt", "báo giá", "Can you send us a quote for this job?", "Anh gửi chúng tôi báo giá cho việc này được không?"],
  ["deliver", "v", "dɪˈlɪvɚ", "giao (hàng)", "We will deliver the goods on Tuesday.", "Chúng tôi sẽ giao hàng vào thứ Ba."],
  ["promote", "v", "prəˈmoʊt", "thăng chức", "She was promoted to manager last month.", "Cô ấy được thăng chức lên quản lý tháng trước."],
  ["forward", "v", "ˈfɔːrwɚd", "chuyển tiếp (email)", "I'll forward you his email.", "Tôi sẽ chuyển tiếp email của anh ấy cho bạn."],
  ["follow up", "phr", "ˌfɑːloʊ ˈʌp", "liên hệ lại, theo dõi tiếp", "I'm writing to follow up on our meeting.", "Tôi viết thư này để trao đổi tiếp về cuộc họp của chúng ta."],
  ["reschedule", "v", "ˌriːˈskedʒuːl", "dời lịch, sắp xếp lại lịch", "Can we reschedule the call to Thursday?", "Mình dời cuộc gọi sang thứ Năm được không?"],
  ["postpone", "v", "poʊstˈpoʊn", "hoãn lại", "The event was postponed because of the rain.", "Sự kiện bị hoãn lại vì trời mưa."],
  ["resign", "v", "rɪˈzaɪn", "từ chức, nghỉ việc", "He resigned because he found a better job.", "Anh ấy nghỉ việc vì tìm được công việc tốt hơn."],
  ["launch", "v", "lɑːntʃ", "ra mắt (sản phẩm)", "We will launch a new phone next month.", "Chúng tôi sẽ ra mắt điện thoại mới vào tháng sau."],
  ["agenda", "n", "əˈdʒendə", "chương trình họp", "What's on the agenda for today?", "Chương trình họp hôm nay có gì?"],
  ["feedback", "n", "ˈfiːdbæk", "phản hồi, góp ý", "Thanks for your feedback on my report.", "Cảm ơn góp ý của anh về báo cáo của tôi."],
  ["strategy", "n", "ˈstrætədʒi", "chiến lược", "We need a new marketing strategy.", "Chúng ta cần một chiến lược tiếp thị mới."],
  ["Best regards", "phr", "ˌbest rɪˈɡɑːrdz", "Trân trọng (cuối email)", "Best regards, Lan Nguyen", "Trân trọng, Nguyễn Lan"],
  ["invest", "v", "ɪnˈvest", "đầu tư", "They want to invest more money in the business.", "Họ muốn đầu tư thêm tiền vào công việc kinh doanh."],
]);
